### ISSUE TITLE
set up pre-commit hooks

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#104]
We could set up pre-commit hooks to make sure that we don't have to deal with resolving style differences in our diffs (e.g. from #103). So the idea would be to have 

- [pre-commit](https://pre-commit.com/) hooks configured
- run the eslint checker
- check if any formatters (e.g. prettier) have complaints

Done when:
- [x] We have a pre-commit hook configuration inside the repo
- [x] this configuration allows to run eslint on all vue and js files in the repo (locally)
- [ ] there is a documentation (either in the README or in a new HOW_TO_CONTRIBUTE file) on how to set up the pre-commit system locally (e.g. how to install it, what tutorial to follow)
- [x] if I follow these instructions in a fresh clone, the pre-commit hook runs when I want to make a new commit
- [x] I can confirm this because there is some terminal output and because if I introduce an error (e.g. trailing whitespace), I cannot do a commit

**Comment by jarmoza** [comment]
Linking this article here as the configuration for precommit package `husky` seems to have continually changed.

Here are up to date instructions on how to install husky and set up new hooks. https://typicode.github.io/husky/#/?id=install

The repo will be updated with a precommit hook for eslint when this branch gets set up for a PR: https://github.com/metaneuro/annotation_tool/tree/precommit-hooks

**Comment by surchs** [comment]
Hey, that does look very powerful. But are you sure we need to re-implement a hook for eslint? Could we just one that people have already written? For example, the pre-commit git org has a number of out of the box pre-commit hooks that you can reuse: https://github.com/pre-commit/mirrors-eslint. Would that do the job for now?

**Comment by surchs** [comment]
This issue is mostly done, we could add a small note to the README.md to explain how to contribute code and make sure the pre-commit hook is working.

**Comment by surchs** [comment]
Closing this and tracking the documentation in the more general project issue: https://github.com/neurobagel/project/issues/33
