### ISSUE TITLE
Should we use provide / inject instead of prop chains

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#105]
I came across this section of the docs (in Vue3, but Vue2 is similar) on prop-drilling as an anti-pattern: https://vuejs.org/guide/components/provide-inject.html#prop-drilling. The proposed alternative is the `provide/inject` tools. I think we should take a look at this section and see if we should adopt that in a future iteration over what we currently have.

_Originally posted by @surchs in https://github.com/metaneuro/annotation_tool/issues/64#issuecomment-1067523939_

**Comment by jarmoza** [comment]
Definitely a useful ability. I don't know if it makes sense for the annotation tool currently. Will be able to speak to that better today after I familiarize myself with the ins/outs of the annotation page's components – in other words, I don't know if our component tree is deep enough to warrant adding it.

That said, from my reading on `provide/inject` yesterday I noted that we lose the ability to check the `type` of injected fields (without a plugin), `required` is gone as it no longer makes sense, and a little bit of extra syntax is necessary to maintain the reactivity of injected fields.

**Comment by jarmoza** [comment]
After working through https://github.com/metaneuro/annotation_tool/pull/108/ it became evident that provide/inject is very useful for us, and will help keep our implementation clean. In this case, it became useful to just have a page provide store data to its components and then the components that need it could inject the fields they need.

@surchs I'd say this is a settled issue.

**Comment by surchs** [comment]
Thanks @jarmoza for implementing this in #108!
