### ISSUE TITLE
Rename pages to 2+ words

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#106]
According to the Vue style guide, an "essential" practice is that component names should be mulit-word (see: https://v2.vuejs.org/v2/style-guide/?redirect=true#Multi-word-component-names-essential).

As pages are actually just components themselves, our page names should become multi-word as well.

i.e. annotation.vue -> annotation-page.vue

**Comment by jarmoza** [comment]
Our linter has not complained about pages named as just one word, but it is now complaining about our default layout (`default`) being just one word.

**Comment by surchs** [comment]
@jarmoza I think this has already been addressed. Could you check that and close?

**Comment by jarmoza** [comment]
There are no complaints from our linter, but this has technically not been addressed since our page names remain as one word. Seeing as we are not reusing them like we would components, I believe this can be closed.

**Comment by surchs** [comment]
Ah, I see. How big of a deal would it be to just move all our page names to two-word names? If it's a lot (which I'd assume), I would move this to icebox and we can deal with it some time later. If it isn't a lot of work, I would say let's just do this now!

**Comment by jarmoza** [comment]
Will try this out briefly now.

**Comment by jarmoza** [comment]
@surchs Just checked into this more. We can do it via the store's `pageData.<pageKey].location` value as this is what is used for routing.

However, another less-documented Vue styling recommendation is that pages do not need to be multi-word. In fact, the reason our linter is not complaining is that in addition to the ignore where we tell the `multi-word-component-names` rule to ignore the default `layout.vue`, there is an implicit carveout with that linter rule for the `pages` folder.

So we're good. And as all of our non-page components are multiword, this can now be closed.

See here: https://github.com/vuejs/eslint-plugin-vue/issues/245#issuecomment-1002209959
