### ISSUE TITLE
Tabs Solution

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#107]
After briefly looking into the issue we were having with Bootstrap Vue tabs and Nuxt, it appears that the implementation of Bootstrap Vue tabs is shaky when it comes to server-side rendering.

Though it's not precisely the same tab doubling issue that we we were having resulting in the need to use the `no-ssr` tag, An example of such an issue where there was trouble rendering tabs on both client and server sides can be found here:  https://github.com/bootstrap-vue/bootstrap-vue/issues/6140

There are a few possible solutions to this problem - which would be good to solve to remove the `no-ssr` workaround.

1.  Seek another implementation of tabs, or
2. If our needs are simple enough, make our own tab component. An example of such a simple implementation can be found here: https://medium.com/notonlycss/how-to-create-a-tab-component-in-vue-js-2812c75807f9, or
3. Hope that an upgrade to Vue 3 and Nuxt 3 will fix the issue.

**Comment by surchs** [comment]
Good idea. What we should probably also do, regardless of the solution we pick, is to change the statement from `no-ssr` which is deprecated and replaced by `client-side` (see [docs](https://nuxtjs.org/docs/features/nuxt-components#the-client-only-component))

**Comment by surchs** [comment]
@jarmoza, is this still an open issue? I would suggest we have a test for the behavior that caused this issue to come up the first time and then close the issue.

**Comment by jarmoza** [comment]
@surchs I think it's possible to write a test case since Cypress will examine the text of the Bootstrap Vue tab. I don't believe the issue is fully resolved. However, I have not seen an instance of tab doubling recently. Have you?

**Comment by surchs** [comment]
No, I haven't seen that either. I'm not super sure from this issue what the original problem was. If you have a clear idea of the behavior and could write a short regression test for that, then I would say let's change the issue to do that and then close it once the test goes in and passes.

**Comment by jarmoza** [comment]
Just to double back because I may be seeing a double tab issue arise in test now. Here's your original comment from `annotation.vue`:

```
        <!--
            TODO: revisit the client-side render solution or remove this comment
            The v-for statement below was causing a mismatch between client-side and server-side
            DOM. In particular, the first element in "pages" (Age) was rendered twice. The error message was:
                Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content.
                This is likely caused by incorrect HTML markup,
                for example nesting block-level elements inside <p>, or missing <tbody>.
                Bailing hydration and performing full client-side render.

            The best answer I found online was this pretty useless stackoverflow answer:
            https://stackoverflow.com/a/61375490/1302009 suggesting that this might be due to some
            async getting of Array data.
            I forced this block to be rendered client-side only for now and that fixed it for now
            See: https://nuxtjs.org/docs/features/nuxt-components/#the-client-only-component
        -->
```

**Comment by surchs** [comment]
@jarmoza: can you write a test that fails because of a double tab condition? If so, that would be a good first step.

**Comment by jarmoza** [comment]
@surchs Turns out I was incorrect about that. Part of my test code was creating an assessment tool group twice.

The `client-only` tag remains in the code surrounding the annotation tabs. I just tried removing it and do not see any duplicate tabs on the annotation page.

Can you confirm? If so, maybe it's time we close this and re-open if the problem re-emerges.

**Comment by jarmoza** [comment]
Closing this per our discussion. If this issue re-emerges we can either reopen this or begin a new issue.
