### ISSUE TITLE
Figure out if we can batch-add multiple files

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#111]
We would like to allow users to add more than one phenotypic file via the file upload interface. We need to figure out:
- does that require different permissions from the single file uploader?
- can we access the file contents?

**Comment by jarmoza** [comment]
@surchs Are we still interested in this batch-add feature or did we decide that users will have to produce this congolomerate input file first?

**Comment by surchs** [comment]
For the moment, we said we'll go with just one file as input. I think we can reopen an issue about this when this becomes relevant again!
