### ISSUE TITLE
I can group assessment tool columns together

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#118]
When I categorize columns, I want to be able to indicate that multiple columns belong to the same assessment tool (e.g. subscales of the same tool), so that
- I don't have to label every column individually with the same concept
- I can indicate the columns that are not allowed to have missing values for this tool to be considered available for a subject

Done when:

- [ ] I can create a new tool group with the user interface on the categorization page
- [ ] A new tool group gets a default name (e.g. tool 1) if I don't provide one
- [ ] Adding columns to tool groups works similarly to mapping columns to age, sex, and diagnosis. I can click on a tool group (or make a new one), and then click on a column to assign it to this tool group
- [ ] I can remove columns from a tool group via the categorization page UI
- [ ] A column can only be added to a single tool group.

**Comment by jarmoza** [comment]
Separate piece of the interface will be for grouping columns, assigning a name - and possibly assigned a ruleset heuristic

**Comment by surchs** [comment]
One thing that would important as well is to document how these groups of assessment tools are stored in the global store so that we can build against this organization when we implement the assessment tool annotation process next.

**Comment by jarmoza** [comment]
> I can indicate the columns that are not allowed to have missing values for this tool to be considered available for a subject

This should be part of a separate issue. I've created one here: https://github.com/neurobagel/annotation_tool/issues/131
