### ISSUE TITLE
I can define a heuristic for assessment tool availability

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#119]
When I annotate, I want to be able to describe a heuristic for when an assessment tool is not available for a subject, so that
- the annotation tool can automatically determine whether a tool is available

Example:
I have a tool with three columns:
| Subject | subscale1 | subscale2 |
|---------|-----------|-----------|
| sub1    | 15        | 16        |
| sub2    | n/a       | 18        |

Then I have previously declared that `n/a` consistutes a "missing value" for column `subscale1`. 
Now I want to be able to describe a rule that if `any` of the columns from the list of `[subscale1, subscale2]` have a missing value, then the tool should be considered unavailable for the corresponding subject. 

So the computed availability for the above example would be:
- sub1: available
- sub2: not available

**Comment by surchs** [comment]
@jarmoza: have we overlooked this issue? I believe this has been implemented already. Can you check and close if that's the case?

**Comment by jarmoza** [comment]
@surchs I believe the best way to describe this is partially completed. We have implemented one heuristic (if one value is marked "missing" for a subject then the subject is deemed "not available." This is tallied in the UI (see `availableSubjects` in the `annot-tool-group` component).

But there is no means for the user to define their own heuristic of availability.

And further, the computed table of subject availability (see computed method `subjectAvailability` in the `annot-tool-group` component) does not appear to be in use at the moment. It is listed as a value in the commented out `transformHeuristics` member of data to be emitted via `update:dataTable`.

**Comment by surchs** [comment]
Ah, yes. Good point. I think then let's keep this issue open but move it back, this isn't a priority at the moment!
