### ISSUE TITLE
Remove the old mockup image

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#133]
We still have the screenshot of the annotation page mockup inside the repo under `/assets`. This should be removed because we don't need it anymore. 

The only other file in `/assets` is the `main.css` and this is in a subdir `/assets/css`, we should consider to:
- pull the stylesheet up one level to `assets`
- rename the `css` dir into `style`
- do nothing and have an emtpy repo

**Comment by jarmoza** [comment]
Done as of https://github.com/neurobagel/annotation_tool/pull/168
