### ISSUE TITLE
Hide unselected categories from the annotation page

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#134]
As a user, when I navigate to the annotation page, I only want to see tabs for categories that I have labeled columns with, so that I get a clear idea of what I have to click on to finish the annotation.

If a category is initially applied to some columns, but then all columns are untagged from this category (e.g. the columns are "removed"), then this category should become hidden.

**Comment by jarmoza** [comment]
I'm going to keep this in the backlog for now as it seems like a reasonable enhancement, though I think it warrants further discussion before implementation.

**Comment by surchs** [comment]
Agreed. On that note: we already came across some situations where we'd like to have more descriptive labels in other repos. Maybe something to discuss on Monday (i.e.: what labels do we need)

**Comment by surchs** [comment]
@jarmoza: do I remember right that you are currently working on this issue as part of something else?

**Comment by jarmoza** [comment]
Fixed by #375
