### ISSUE TITLE
Let user declare missing values for all columns of a assessment tool group

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#135]
After I have indicated that one or more columns belong to the same assessment tool, I want to be able to label / designate the missing values for all of these columns, so that I can tell the annotator when an assessment tool is available.

We will make some assumptions for our first iteration:
- only columns that have to be present (i.e. not-missing) are annotated as belonging to the assessment tool. In other words: we don't have to ask the user again to tell us which columns are important, we just treat all annotated columns as important
- an assessment tool (i.e. group of columns) is considered to be "available" or "not missing" for a subject, if the values in all of the labeled columns are not missing. i.e. if the entry for a subject is `{ columnA: "missing", columnB: "not missing"}`, then the whole thing is considered missing. We can change that in the future by letting the user pick a any or all strategy

**Comment by surchs** [comment]
@jarmoza: I think this has been implemented with your tool group work. If you agree, would you close this?

**Comment by jarmoza** [comment]
Yes, this is completed as of https://github.com/neurobagel/annotation_tool/pull/159
