### ISSUE TITLE
should we do consistent variable notation

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#136]
We are now using a type of hungarian variable notation for parameters passed to methods (`p_parameter`), for example [here](https://github.com/neurobagel/annotation_tool/blob/master/store/index.js#L298). But for variables declared inside methods, we are not using this type of notation. I think that if there is a benefit to this type of notation, we should try to use it consistently throughout the codebase. And if the benefit is not so great that we don't want to use it consistently, then I think we should stop using it alltogether in order to avoid confusion ("why does this parameter have a single character prefix and what does the prefix mean"). 

If we do adopt it consistently, it would be good if we could find some way of checking for this type of notation. Maybe eslint has a rule?

**Comment by surchs** [comment]
wdyt @jarmoza, I think you introduced the hungarian notation for the store methods. Maybe we could collect a couple of these and then deal with them in a bigger linting related epic?

**Comment by jarmoza** [comment]
> Maybe we could collect a couple of these and then deal with them in a bigger linting related epic?

I think so.

As I've mentioned before, I use the `p_` Hungarian notation for an instant visual cue that this is a parameter and not a local or global variable. In other languages with features like stronger typing and class security, I often use more Hungarian notation as reminders but neither make sense in this context.

**Comment by surchs** [comment]
@jarmoza, could you do a quick parse of the annotation_tool issues, see which ones would make sense to bundle together for future fixing, and then close this issue (and the other individual ones)?

**Comment by surchs** [comment]
@jarmoza, I'd be in favour of closing this - wdyt?

**Comment by jarmoza** [comment]
Yes, I was just looking this over earlier and then going through potentially stale issues, but got sidetracked. 

Yes, I think this can be closed. To the point of the hungarian notation, it being different is the point in this instance. It differs from locals/globals.

My remaining question is if you would like to do this still:

>see which ones would make sense to bundle together for future fixing

**Comment by surchs** [comment]
I think it makes sense, but seeing how we didn't get to it so far, I'd say let's close and have this come up again on its own. Not perfect but better than keeping issues around as a reminder, I think

**Comment by jarmoza** [comment]
Sounds good.
