### ISSUE TITLE
I get a preview of samples for whom an assessment tool is available

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#139]
As a user, 
when I am declaring missing values for a tool group on the annotation page, 
I can see a preview of a subset of samples / subjects that would be considered to have / not have the current tool, based on my selection of missing values, 
so that I can more easily spot a mistake I may have made during my missing value selection.

Done when:
- [ ] there is a component that shows a (reasonably small, e.g. < 10) selection of rows for the columns assigned to the current tool group. 
- [x] each row includes the subject / sample ID, the values for the columns mapped to the tool group (but no others), and a visual indication of whether this row (sample) is currently considered to be available or unavailable (e.g. red or green)
- [x] assigning or unassigning values as missing elsewhere directly updates this preview (e.g. preview is live)
- [ ] preview is inside an accordion so it can be hidden on smaller screens or to save space
- [ ] accordion starts out expanded

**Comment by jarmoza** [comment]
>each row includes the subject / sample ID, the values for the columns mapped to the tool group (but no others), and a visual indication of whether this row (sample) is currently considered to be available or unavailable (e.g. red or green)

The new missing value implementation for tool groups allow users to mark a value as missing. Instead of flipping between red and green, the value disappears from the tool group component and appears as a missing value in the missing value component above – just like every other annotation tab.
