### ISSUE TITLE
Should we sort properties and methods alphabetically

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#141]
This came up in the discussion of #132. There is a eslint rule to force all properties and methods to be sorted alphabetically: https://eslint.vuejs.org/rules/sort-keys.html

Pro:
- this could make the app structure more predictable

Con:
- this may prevent us from grouping related methods and properties together in space and thus spaghettify our code

We can discuss here if and how to implement (e.g. only for methods, not for parameters, ...).

_Originally posted by @surchs in https://github.com/neurobagel/annotation_tool/pull/132#discussion_r868348066_

**Comment by surchs** [comment]
I believe that this has been addressed by the new eslint rules and we do now force attributes to be organized alphabetically. Is that right @jarmoza?

**Comment by jarmoza** [comment]
This has not yet been added to `.eslintrc.js`, but can be.

The appropriate rule is here: https://eslint.org/docs/rules/sort-keys

Our current scheme would be ascending, non-case sensitive ordering. There are other options listed in the link above but those two should take care of our case.

The addition to `.eslintrc.js` would be:

```
{
    "sort-keys": ["error", {"caseSensitive": false }]
}
```

(Ascending order is default.)
