### ISSUE TITLE
Address lingering white-space issues

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#142]
This came up during review of #132. We have eslint and we have rules. But there are still some style aspects where we have freedom of choice and if we chose differently, we'll get these useless whitespace diffs. The main goal is to avoid these and to pick something we can live with that is consistent.

quote from the PR

> We already have 12 additional rules defined. This particular rule does not seem to have an exact correspondence among eslint rules, so we may have to set several additional rules. I'm against coming up with our own, custom neurobagel styleguide - that seems like a lot of work for something relatively unimportant. But we still want to make sure that we avoid all of this whitespace diff stuff. So I think we have two options:

1. Pick any existing style guide that is sufficiently restrictive to cover any white-space diff cases (e.g. google, airbnb) and stick with that. That would also mean removing our own exceptions to this style guide.
2. setting up prettier again as a code formatter to actively enforce certain style rules that the linter may not care about. 

Between the two, I prefer 1 because 2 will be additional work to set up. In both cases we'd have to check that this actually solves the white-space around parantheses case. 

What do you think @jarmoza ?

_Originally posted by @surchs in https://github.com/neurobagel/annotation_tool/pull/132#discussion_r868407471_

**Comment by surchs** [comment]
@jarmoza, I think with #156 this could be closed. Do you agree?

**Comment by jarmoza** [comment]
Yes, agreed.
