### ISSUE TITLE
I can add missing values for numerical tool-groups

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#146]
the process of adding new missing values works both for categorical data (i.e. few unique values) and numeric data (i.e. many unique values) without permanently spamming the screen with a long list of values (e.g. dropdown)

**Comment by surchs** [comment]
@jarmoza, this guy probably needs a little bit more detail. Mind having a look over?

**Comment by jarmoza** [comment]
Sure. What prompted you to mention it? Is there something you've come across in your work?

**Comment by surchs** [comment]
It's part of the epic you are working on right now and I wanted to make sure we think through it before the next sprint so that we have a clearer idea of the work involved by then.
