### ISSUE TITLE
What elements should be modifying global store objects

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#155]
We are currently trying to keep all store access limited to pages and then send down these data to components via props or provide/inject calls (see #105). The idea behind this was that having only a few, central places from where we modify the store would make things easier to understand and debug (see also #64).

The downside is that a lot of information has to truck up and down the tree from these pages to the components where the information are actually displayed and where the user interacts with the app.

Now that we have worked with this pattern for a little bit, let's collect some observations on whether this actually makes things more clear as we had expected, or whether we could do without. Without here would mean, any place that needs to can directly talk to the global store, regardless of it's level in the tree hierarchy.

**Comment by surchs** [comment]
One example where we have recently run up against this is when we wanted to use v-model on a form element that directly affects a variable stored in the global store (#154). The recommended way of implementing this uses direct store calls from a computed property inside the component. So in this particular case, not allowing direct store access makes our live hard, because we need to write more complex logic to have v-model work.

**Comment by jarmoza** [comment]
Though cases of `mapGetters`, `mapState`, and `provide/inject` most often functionally equivalent (although we've seen a recent exception where an injected store field cannot be watched by a child component unless its store name is fully spelled out, e.g. `$store.state.fieldName`), it would be good to revisit how we want to consistently provide fields like this to child components.

For instance, looking at the current `provide` list in `annotation.vue` reveals something that may be too much. (It could very well be that after examining its uses by child components that this could be just fine too.)

```
        provide() {

            return {

                // Getters
                columnDescription: this.columnDescription,
                isMissingValue: this.isMissingValue,
                valueDescription: this.valueDescription,

                // Store fields
                columnToCategoryMap: this.columnToCategoryMap,
                dataDictionary: this.dataDictionary,
                dataTable: this.dataTable,
                missingColumnValues: this.missingColumnValues,
                missingValueLabel: this.missingValueLabel,
                toolGroups: this.toolGroups
            };
        },
```

**Comment by jarmoza** [comment]
Closing this as we have adopted the paradigm of allowing child components direct access to the store's getters, actions, and mutations. (Nobody except mutations and getters have direct access to Vuex `state`.)
