### ISSUE TITLE
Requirement for 'participant_id' as subject ID field

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#157]
Now that we have reached a point where subject ID is required to annotate part of our data – in this case for the availability of tool groups by subject – a subject ID field must be required in the data table input (`participants.tsv`) into the annotation tool.

With that in mind, we should disallow attempts to upload a `participants.tsv` file without a column `participant_id` for subject IDs and present an message on the landing (home) page explaining the error.

Currently, the workaround for this issue is that the criteria for entry into the annotation page from the categorization page has been amended to require users to categorize one column as 'Subject ID'.

Along with the above change, the ability to categorize a column as 'Subject ID' should be removed.

Subtasks for completion:
- [ ] Home page blocks upload of `participants.tsv` files without a `participant_id` column and presents a message explaining the error
- [ ] 'Subject ID' is no longer a category listed on the categorization page for linking with data table columns

**Comment by surchs** [comment]
This is a great point. I would add: when we implement this step to validate uploaded data, then we can stop asking people to categrorize the `subject_id` column and instead do this automatically.
