### ISSUE TITLE
Revisit subject availability logic in tool group annotation component

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#161]
@surchs Made the following comments about the current subject availability implementation for the `annot-tool-group` component.

>Just commenting here for the future: there is some pretty fancy magic going on to keep this guy in sync with changes outside of the component (indirect listening to changes in the missingValue store variable). Because these links are largely implicit (listenting to a local variable because it can be changed by another listener calling a method, and so on) I believe this will become hard to remember right quick, so it might be a good candidate to have another look at in the future and maybe move it to the store.

>Also commenting for the future here. Currently, a subject is not available for the current tool if ANY of its values in the relevant columns are "missing". The current implementation works, but probably needs to be rewritten once we allow for other availability "rules" that have to take into consideration of the other columns (e.g. if ALL have to be missing for a subject to be not available).

The task here is to revisit the internal logic for this functionality to iron out any brittleness and make it more flexible for future availability criteria

**Comment by surchs** [comment]
@jarmoza, can you take a look at the code and the original context and find the code section that this comment is referencing? With this we can discuss what to do about it or if these sections have already been removed through some other PR.

**Comment by jarmoza** [comment]
@surchs Take a look at my recent comments in https://github.com/neurobagel/annotation_tool/issues/119. I note the pieces of code currently involved in subject availability there as well as the single heuristic we have implemented without other options for users.

**Comment by surchs** [comment]
OK, thanks! I think we can also put this one on ice for now.

**Comment by surchs** [comment]
Closing this because we are re-implementing the assessment tool availability workflow
