### ISSUE TITLE
Standard app page initialization code for testing

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#166]
Currently a page's initial state cannot (always) be loaded with a few simple store actions. Page load is brittle because of actions required for their initialization being separated between the store and mount functions.

For example, the categorization table is not created until requirements are met on the index page for the user to navigate to the categorization page. This results in non-standard/disparate page loading code and makes for creation of tests for pages more difficult to setup as well as more opaque.

The ideal solution would be to create a standard for page load, for example, where an initial state is created via store actions. A page's early Vue lifecycle hooks (e.g. `created` or `mounted`) can then call the required page state initialization actions in the store – making the location of such code standard across pages and making the creation of tests more intuitive and less research-intensive for the test creator.

**Comment by surchs** [comment]
Hi @jarmoza, do you have an example with a reference to the code / component of what you're describing?

**Comment by jarmoza** [comment]
This had been split across `created`/`mounted` Vue hooks and a method in the store to check the store state for next page access. However, the former store data structure initializations are explicitly defined in the store state, and the latter has been moved to the new `pageAccessible` getter used by the `next-page` and `tool-navbar` components.
