### ISSUE TITLE
Provide examples of stored variables

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#170]
When I go and look at the store, variables are empty and there is some code to intialize them.
This is hard to understand because now I don't know how this variable will look like once it is initialized.
We need one of these

- detailed documentation of the variables at runtime
- inline comments explaining the format of the variables once they are initialized

**Comment by surchs** [comment]
This was initially a drafted issue from a good while back. 

I think another way of thinking about this problem is with tests. If I have tests for components that mount the component and supply them with the correct format of data, then the test shows me how to use the component. And the test is kind enough to break when the supplied data no longer works - unlike some inline doc.

**Comment by jarmoza** [comment]
This is conceptually linked to https://github.com/neurobagel/annotation_tool/issues/166

> Currently a page's initial state cannot (always) be loaded with a few simple store actions. Page load is brittle because of actions required for their initialization being separated between the store and mount functions.
> 
> For example, the categorization table is not created until requirements are met on the index page for the user to navigate to the categorization page. This results in non-standard/disparate page loading code and makes for creation of tests for pages more difficult to setup as well as more opaque.
> 
> The ideal solution would be to create a standard for page load, for example, where an initial state is created via store actions. A page's early Vue lifecycle hooks (e.g. created or mounted) can then call the required page state initialization actions in the store – making the location of such code standard across pages and making the creation of tests more intuitive and less research-intensive for the test creator.

**Comment by surchs** [comment]
Closing this because runtime store variables are now accessible via our component and store-unit tests
