### ISSUE TITLE
Initial page-specific tests for Download page

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#175]
In line with the initial work from https://github.com/neurobagel/annotation_tool/issues/69 and https://github.com/neurobagel/annotation_tool/pull/165, this task is to complete initial, page-specific tests of the download page's file transformation and download functionality. Each test will be preceded by a specific programmatic state load from the annotation page.

App work required:

- [ ] Have the app store a copy of the recently downloaded json contents in the store. This will enable Cypress to assert whether or not the contents of the file are correct.

Planned tests include:

 - [ ] Download of json file and content verification. State loaded: Annotation page has annotated a single column
 - [ ] Download of json file and content verification. State loaded: Annotation page has annotated multiple columns
 - [ ] Download of json file and content verification. State loaded: Annotation page has annotated an assessment tool group
 - [ ] Download of json file and content verification. State loaded: Annotation page has annotated multiple columns and an assessment tool group

Since only our example of simple, 'good' data will be used, expected behavior of all tests above is to have the output json file downloaded and its contents verified as consistent with the loaded annotated data table.

**Comment by surchs** [comment]
Closing this as tests will be taken care of as part of the refactoring (https://github.com/neurobagel/annotation_tool/issues/251)
