### ISSUE TITLE
Categorical annotations not in output if saved more than once

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#176]
Steps to reproduce:

- have a "categorical" column (e.g. Sex or Diagnosis)
- annotate the values
- hit "Save"
- make a change to any mapping
- hit "Save again"
- go to Download page

Expected behavior:

- Download page shows the last "saved" mappings

Actual behavior:

- Download page shows empty mappings for the column

**Tests**:
Not sure if these are better tested as component tests for the categorical annotation procedure or e2e of the entire annotation experience.

If I categorize a column as "Sex" (or "Diagnosis") and then completely annotate the values of that column:
- [x] then the store should not be updated (or component shouldn't emit an update event) if I haven't hit "save" yet
- [x] once I hit "save", the store should be updated (and/or component should emit update event with the correct data)
- [x] if I change the annotations after I have already made annotations and hit save a second time (more than once), then the store should reflect the newly updated annotations (or component emit update event with new data)
- [x] when I navigate to the download page after a 1+x annotation save workflow, the download page column should contain the mappings I have just created (i.e. the words should appear, order is irrelevant)

![Image](https://user-images.githubusercontent.com/1302022/185973134-190d03a3-bab1-49eb-99f7-c8e6ba52caf9.gif)

**Comment by surchs** [comment]
I added some test cases that I think would prevent this from being reintroduced down the line. Let me know what you think @jarmoza.

**Comment by jarmoza** [comment]
Thanks @surchs. This issue could be a good basis to now try a component Cypress test. I do believe that writing an "e2e"-ish test is proper as well.

The idea being that once the component test(s) (for likely each of the different annotation tab components) is written, at least one e2e test should be written to ensure this saving of annotation twice shows up properly in the table on the download page.

**Comment by surchs** [comment]
I think that's a good idea for getting more test coverage while you chase this bug. If you can write a e2e / outside / behavioural test that reproduces this bug first, then that would be a great indicator of when a fix is working - and also a good future regression test.
