### ISSUE TITLE
Add documentation on how to add new tests to our e2e system

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#177]
As a contributor to neurobagel, I want to have a documentation of how to add a new e2e test and where to find additional learning resources, so that I can easily get started with testing my new code contributions while I work on them.

- [x] There is a brief documentation on how to create a local dev environment that can run tests
- [ ] The documentation is easy to find (e.g. linked prominently on the main repo page)
- [x] The docs contain an explanation on how to run the tests on the CI system / confirm that the tests succeed before merging

**Comment by surchs** [comment]
@jarmoza: do we have any documentation on this already?

**Comment by jarmoza** [comment]
As I've just posted the current e2e and component testing documenation in [our org's Google doc](https://docs.google.com/document/d/18z4IkwNcEd9V4KNDUvsuBtsWI_lWO8sVJL51EDKXJi8/edit#), and have removed the temporary markdown file from the annotation tool, I'll address this issue now.

**Comment by jarmoza** [comment]
> The documentation is easy to find (e.g. linked prominently on the main repo page)

A separate Neurobagel project task has been created for this here: https://github.com/neurobagel/project/issues/56
