### ISSUE TITLE
Decouple page load from app state and initial page state loading

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#179]
For the purpose of testing (and likely overall app stability in the future), each page in the annotation tool should be loadable without reliance on the state of the store. That is, each page should be able to load its components safely without erroring.

This problem arose during the creation of Cypress-based, page-specific tests for the app.

The current workaround for tests is to load the state of the store as need be and to use Vue `route` to access to the page. This exposes a brittle section of the annotation tool's code. Direct page visits should be possible without crashing the app.

The proposal for this enhancement is as follows:

- [ ] Isolate the necessary minimum state for page load (index, categorization, annotation, and download)
- [ ] Offer safety checks on critical variables in the store to prevent crash upon page load

and the following task:

- [ ] Create a generic function for page loading in the store which is responsible for properly and safely setting up the requisite store variables for each page (if necessary). It is listed as a separate issue here: https://github.com/neurobagel/annotation_tool/issues/180

**Comment by surchs** [comment]
@jarmoza: could you describe the problem with an example here. What is currently causing a problem and how would you reproduce this problem (e.g. with a test that doesn't work)?

**Comment by jarmoza** [comment]
The simplest reproduction of the issue for the overall app is this.

1. Run the npm dev server
2. Try to go to any page directly other than home or`/categorization`. `/annotation`, and `/download` both fail to load.

The test case for either would be checking to see if any page component loads - even the nav bar.

From there we would want a test more meaningful: namely that the store is set up in a consistent state so that we can ensure navigating back to the 'home' page guarantees we can run through the annotation process of a dataset without error.

This is also the reason that implementing a store based method for consistent, independent page loading would be helpful to undo this brittleness in the annotation tool app.

**Comment by surchs** [comment]
I think this is linked to the issue (s?) we made about writing down the input and output requirements of each page / component as part of our internal docs. Here is one of them: https://github.com/neurobagel/annotation_tool/issues/64

@jarmoza: if you find others, please also add them here. I think writing these docs is a separate issue but it might be helpful for this problem here.
