### ISSUE TITLE
Initial page state loading enhancement  - direct page access/single page setup function in store

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#180]
This is a subtask/extension of https://github.com/neurobagel/annotation_tool/issues/179. The idea here is to create a store function that knows how to correctly setup the variables necessary for that page in order to create a safe load of the page via direct access (either browser bar, Vue routing, or test functions like `cy.visit`).

It's possible that such a function could be called in general fashion in an appropriate lifecycle hook of each page (either `created` or `mounted`)*

This, of course, does not include the setup of variables in the `data` object of each page.

**Comment by surchs** [comment]
closing as related to https://github.com/neurobagel/annotation_tool/pull/233
