### ISSUE TITLE
Assessment tool shows up in output even if not assigned

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#186]
Steps to reproduce:

1. Load participants.tsv
2. Do not classify any column as "assessment tool"
3. proceed with classification and annotation of other columns as needed
4. export the .json output

Expected outcome:
Only the categories that have been mapped to columns in the data are part of the output.

Actual outcome:
There is an empty "assessment_tool" attribute with an empty array included or each subject:

```json
{
    "name": "my_dataset",
    "type": "dataset",
    "subjects": [
        {
            "id": "sub-1234",
            "age": 111,
            "sex": "other",
            "assessment_tool": []
        },
]}
```

Test 1:

- I load data and then categorize nothing (only map the participant_id column)
- go directly to download the output
- then the output should only contain an array of subject objects that have an "identifier" attribute with the subject ID

Test 2:

- I load data and categorize some data (e.g. I map a column as "about" sex), but not any for assessment_tool
- I then annotate the mapped column (e.g. the unique values of "sex") and save
- I navigate to the download page and download the harmonized output
- then the subject objects in the subject array should not contain an attribute for "assessment_tool"

**Comment by jarmoza** [comment]
Marking this as `wontfix`. The output format of the annotation tool will now be changing with its new focus on an annotated data dictionary.
