### ISSUE TITLE
Check out Dandi Annotation

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#187]
Dandihub has their own meta data annotation thing going on. It's worth it to see what they are doing, and if we can get good ideas from them (or suggest some of our solutions to them).

@jarmoza: can you make an account / log in with github on https://gui-staging.dandiarchive.org and try it out?

**Comment by jarmoza** [comment]
Beginning this task.

**Comment by surchs** [comment]
@jarmoza: is this still blocked or are you working on it (shows as "doing" for me)

**Comment by jarmoza** [comment]
@surchs No, access actually came right away even though they said it would take a few days. Just wasn't sure where to prioritize this given our recent discussions on researching what it takes to get sessions into the annotation tool. I've just moved this to 'Next' to make things clear.

**Comment by jarmoza** [comment]
I thought I moved this to Backlog earlier in the week?
