### ISSUE TITLE
Understand impact of changing to data dictionary output

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#201]
We want to understand how many components and what part of the store logic is affected by changing from the current internal representation of "table that gets updated" to "data dictionary that gets updated".

Let's start by taking a look at the components and figuring out which ones of them:
- depend on the annotated datatable in the store
- affect the annotated datatable via their output (events or other)
- have internal logic that expects something looking like a table (i.e. array of objects where each object is a row)

Let's do that in [this google spreadsheet](https://docs.google.com/spreadsheets/d/1JGb8oo_AgG0at6_YIfJrwaaKbBgwhd0wuZArYGhDyUw/edit?usp=sharing) for now (feel free to add more columns if needed).

Let's keep track of store edits here: https://codeshare.io/r9WllY

@jarmoza

**Comment by jarmoza** [comment]
I am making an interview of where `dataTable`, `dataDictionary`, and `columnToCategoryMap` are used, organized by component/page. Will attach that here.

**Comment by jarmoza** [comment]
Something else to note is to remember now that we're doing testing that changes to the app/store affect tests!

**Comment by surchs** [comment]
@jarmoza: as we implement the components with the new data flow, I have started updating our [codeshare]([ttps://codeshare.io/r9WllY](https://codeshare.io/r9WllY)) with the examples I'm using in my tests. I also started differentiating the type of data handler (e.g. `prop` vs `getter`) to make it easier to see where stuff comes from. Let me know what you think

**Comment by jarmoza** [comment]
@surchs Missed this comment. I think this is a good idea. I'll start doing it as well.
