### ISSUE TITLE
Write component and page specifications

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#202]
This is a collection issue to track the specifications for all our components.

As part of our refactor to output a data dictionary, we need to write specifications for the components of the annotator app. Each specification should state:

- the purpose of the component
- what actions / user flows it supports
- what input data are required to enable this functionality
- what output data are generated / affected
- what (if any) internal state needs to be held in the component (because it doesn't have to be shared)

The specification should not contain implementation details. Instead the specification should be written as a human readable template for component tests, i.e.: "when I get this data, and then click over here, this thing will come out".

Here are the pages (page level components) that need to be spec'd:
- [x] #214
- [x] #215
- [x] #216
- [x] #217
- [x] #218

Here are the components that need to be spec'ed:
- [x] #203
- [x] #204
- [x] #205
- [x] #206
- [x] #207
- [x] #208
- [x] #209
- [x] #210
- [x] #211
- [x] #212
- [x] #213
- [x] #248

Draft to combine the state that components need into a shared thing: https://codeshare.io/r9WllY

**Comment by surchs** [comment]
Things I noticed while going through the components:

- the save-annotation button logic is replicated in several annotation components (age, categoricalm vocabulary). I think we can
  - refactor the button into a separate component and reuse it
  - have all annotation components save state automatically and just remove the button
  - some third thing that's smarter
- the age annotation component calls the lower-level `continuous-values` component. The latter one is essentially just a wrapper around a table. We probably thought we'd reuse it somewhere else, but so far we haven't. I wonder if we could do any / all:
  - merge age and continuous component (i.e. remove the lower level component)
  - make the age component more generic and into a "pick and preview a transformation heuristic for a continuous variable" component
- the discrete-value component and the vocabulary component are very similar. The main difference right now is that for discrete-values we provide a list of allowed values, whereas for the vocabulary we provide free form text fields. But the idea behind both is that you take categorical values and map them to terms from a controlled list (we only haven't implemented that for things like diagnosis). I believe it would make sense to merge the two into a more generic "discrete value" workflow. For now we could:
  - just make everything freeform text entry (including the values for sex). OR
  - have a hard-coded list of diagnosis values until we figure out how to get this list directly from an API.

**Comment by jarmoza** [comment]
1. I still like the idea of participatory save functionality. The only trick about save annotation button for each component is how to inject any custom functionality that needs to happen when it is clicked
2. Re: continuous values component. I think we should err on generic with parameters given future configurable categories.
3. Having a hard-coded list of diagnosis values makes the most sense for now re: discrete value component until we figure out the controlled vocab API. Also, the hard coded list will be better for any interim demos than free typing a string

**Comment by surchs** [comment]
Yeah, I think I feel mostly the same here. 

re 1: 

> The only trick about save annotation button for each component is how to inject any custom functionality that needs to happen when it is clicked

Yes, you're right. In fact, because the button component shouldn't really do any of the "saving" itself, the most likely result would be that it just emits a generic "saved" event that the partent component needs to handle. And at that point we have just wrapped a generic button in a useless button component. So maybe we should just leave things like they are and have the button be part of the component.

re 3: 
agree. I think this may be a good intermediate solution!

**Comment by surchs** [comment]
If we keep the `"save"` button, one thing we could consider adding is a generic `"confirm save"` component that could pop up a [toast](https://bootstrap-vue.org/docs/components/toast) when the save action has successfully completed.
