### ISSUE TITLE
specify file-selector component

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#203]

**Comment by jarmoza** [comment]
Purpose: Allow user to select tsv or json file and emit that file data to parent component

Actions / User flows:
	1. Click file select button
	2. User selects file from system dialog
	3. User can cancel file selection from system dialog

Required input:
	* content type (string, either 'tsv' or 'json' supported)

Generated output:
	* object with file data and filename are emitted to parent

Internal state:
	* file input object - which contains filename (computed property for fileInput.name if it exists)

**Comment by surchs** [comment]
I agree, this component is probably not one that should talk to the store directly and instead emit events to the parent.

**Comment by surchs** [comment]
Based on the [draft of the components and store methods](https://miro.com/app/board/uXjVP8wIUms=/?share_link_id=99546673675) I think this is supposed to talk to the store actions directly after all. Specifically the

- `saveDataTable` and
- `saveDataDictionary`

actions.

**Comment by jarmoza** [comment]
Yes, that's correct. I've adjusted the [Miro diagram](https://miro.com/app/board/uXjVP8wIUms=/) to reflect this.

**Comment by surchs** [comment]
Great, thank you. Closing this now.
