### ISSUE TITLE
specify column-linking component

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#205]
## purpose

Show me the names of columns in the tabular input file and their descriptions from a data dictionary (if available), so that I can make a decision on what category I should map each column to

## Use cases and input / output

- Show the column names of the input file in the order of their appearance
  - input: 
    - a list of column names
  - output:
- Show, if available, the column descriptions from the data dictionary next to the column names
  - input:
    - column description / data dictionary (object)
      - keys are the column names
      - values are the human readable descriptions
  - output:
- if I click a column name (e.g. table row), it gets assigned to the currently selected category (app state) - unless it is already assigned to the category, in which case it gets unassigned (i.e. is not assigned to any category)
  - input:
    - the currently selected category
  - output:
    - the name of the clicked on column name, such that a mutation can map it to the currently selected category
- a column (e.g. row) can be mapped to a category. If a column is mapped to a category, then the column element (e.g. table row) is colored with the color corresponding to the category
  - input:
    - column to category mapping (object)
      - keys are column names
      - value is the category name the column is mapped to (one column can be assigned to one or none categories)
    - category specification (object)
      - keys are category names
      - values contain the color of the category
  - output:

input draft:
```javascript
columnList = {
    "column1": {
        description: "Some description",
        category: ""
    }
}
currentCategory = "category1"

categoryList = {
    "category1": {
        "color": "blue",
        ...
    }
}
```

## Internal state
The component doesn't have to have any internal state

## Future use cases / ideas

- column names mapped to the currently selected category (app state) are visually emphasized (e.g. brighter color) and column names mapped to categories that are not currently selected are visually muted (e.g. less opaque)
  - input
    - column to category mapping (see above)
    - the currently selected category

**Comment by jarmoza** [comment]
There's a small but perhaps useful question to consider here regarding where information for the app should go. In this case, I'm thinking of the `selectedCategory` field of the categorization page. Since this is a UI-specific field, should it not live on the page. You can see how the `category-select-table` and `column-linking-table` interact with this field via emitting events to the categorization page (see `setSelectedCategory` and `tableClick`).

**Comment by surchs** [comment]
Yeah, agreed. That's a good question. I think a general rule could be that if:
1. the data / variable is needed or accessed by another component, then it should live in the store (i.e. default to no prop passing). OR
2. if the data / variable should stay the same when the page is visited again. 

So two components here need to know what the currently selected category is: the category-selector and the column-table. So in my view it could go in the store and be passed directly. But I agree that we could also keep it in the categorization page and pass via prop/emit. If we do that though, then the current category will always reset to default when we come back to the page - currently that would not be a big deal (not sure if later it might, but that shouldn't matter).

I'm personally leaning more towards keeping it all in the store unless its something that doesn't need to be shared outside a component and to just avoid emits / props in general. My reason for that is mostly consistency. But if you can think of a reason for why that'll be a bad choice, then we should discuss it now.

**Comment by surchs** [comment]
ok, we let the page hold the currently-selected category name - also to be consistent with local state holding on the annotation page
