### ISSUE TITLE
specify category-tool-group component

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#206]

**Comment by jarmoza** [comment]
Purpose: Create tool groups composed of columns linked to the 'Assessment Tool' category

Actions / User flows:
1. Create tool group
2. Remove tool group
3. Modify the tool group

Required input:
* column names - At least one column linked to the 'Assessment Tool' category (via `category-select-table` and `column-linking-table)
* getters `getGroupOfTool` and `isToolGrouped`

Generated output:
* tool group action emitted with object containing action name (create or modify) and data (includes name of tool group and list of its tools)
	- both modify p_state.toolGroups and p_state.annotationDetails
* remove tool from group action emitted with object containing tool name and group name
	- modifies p_state.toolGroups in store

Internal state:
* watch on columnToCategoryMap
* keeps track of tool groups (assessmentToolGroups.items)
* current selected group name (currentGroup)
* 'mode' - create or modify (currentMode)
* new tool group name (newToolGroupName)
* tools selected by user with multi-select box (selectedTools)
* whether or not a column in its available columns has been selected (columnOptions)
