### ISSUE TITLE
specify annotation-tab component

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#207]
Purpose: Generic container for primary components of each annotation tab (explanation, columns for annotation, missing values, specialized annotation component)

Actions / User flows:
N/A

Required input:
* activeCategory: the tab needs to know what category it is handling, so it can pass that via prop to its own children
* annnotationComponent: I need to know whether I am handling annotation for a categorical or continuous variable. I should be able to ask the store what annotation component I am supposed to load for the user.

Generated output:
* none

Internal state:
* none

**Comment by jarmoza** [comment]
Purpose: Generic container for primary components of each annotation tab (explanation, columns for annotation, missing values, specialized annotation component)

Actions / User flows:
N/A

Required input:
* details - set of info about each annotation tab from the store (state.annotationDetails)
* title - title of the annotation tab, sent to the specialized component
* column to category map from store
* data table from store

Generated output:
* emits remove column event to annotation page
* emits remove missing value to annotation page
* emits update missing column values to annotation page
* emits update for data table to annotation page
* emits update for 'heuristic' to annotation page (but is not handled)
* emits update for missing value to annotation page (addMissingValue - on annotation page)

Internal state:
* title of the current tab
* category table
* getColumnsOfCategory from store
* filtered data table
* relevant columns
* unique values
* unique values to subject map

**Comment by surchs** [comment]
Two things:

1. If the annot-tab doesn't have any user actions of its own (I agree that it doesn't), then it should probably not have to handle any data flow either (child components can be in charge of that themselves)
2. I think with the refactor we're moving a ton of responsibility from the pages to the components. This annot-tab thing now feels a lot like it could just be [a dynamic layout](https://nuxtjs.org/docs/directory-structure/layouts/) rather than a component.

**Comment by jarmoza** [comment]
Agreed on 1 and 2! This feels like some good progress regarding our Vue/Nuxt development experience.

**Comment by surchs** [comment]
This thing needs to know what type of category it is handling (categorical or continuous)

**Comment by jarmoza** [comment]
Closed by https://github.com/neurobagel/annotation_tool/pull/242
