### ISSUE TITLE
specify annotation-age-values component

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#208]
## Purpose

Show me a subset of the continuous values in the columns I am currently annotating, so that I can pick / confirm the appropriate transformation heuristic to turn the values into the desired output format.

## Use cases and input / output
- [x] It shows me a selection of N (configurable ?) unique raw values for each column mapped to this category (e.g. age), so that I can determine their format / encoding and select the appropriate transformation heuristic
  - input:
    - unique values of columns (object)
      - keys are column names
      - values are arrays of unique values to be displayed (excluding missing values)
  - output:
    - none
- [x] I can select among a list of category specific transform heuristic options the one that I think fits my data best, so that I can see and confirm the transformed data, and so that the format / encoding will appear in my eventual output data dictionary
  - input
    - list of transform heuristic names for the current category
  - output
    - the name of the user selected transform heuristic
- [x] I see the currently selected transformation heuristic applied to the raw data, so that I can check it and possibly change it if it doesn't work well.
  - input
    - the corresponding transformed values to the unique values already displayed
  - output
    - none

## Internal State
The component doesn't need internal state

## Future ideas
- I can supply the allowable range of values (min, max) so that the tool can guess for me what outliers / missing values are.
- I can provide a unit for the raw values, so that the transformation can use this information and we can add the unit to the data dictionary
- there is a way to select missing values from among the values in the continuous values (might have to be a separate component / workflow?)

**Comment by jarmoza** [comment]
Unless it gets too specific, it's possible make an `annot-continuous-values` component that can be parametrized to flag on age transformation functionality/UI pieces.

**Comment by surchs** [comment]
Yes! I agree and I think that's what we should try to do here.

**Comment by surchs** [comment]
For this implementation I will just build a "select my heuristic" for the entire category (any column mapped to the category). There may be a future use case where we want to select different heuristics per column, but for now a single selection is enough.
