### ISSUE TITLE
specify annotation-continuous-values component

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#209]
This is a very low level component as currently built. I think we should check if we can merge it with #208

**Comment by jarmoza** [comment]
@surchs One thing we could also do beyond genericizing this component is to make that future, generic version parametrizable. So if we do have a specific need - like performing common age value transformations - we can have a way of flagging that transform attempt on via props.

**Comment by surchs** [comment]
Closing this because we'll subsume it in #208 as the new continuous value component
