### ISSUE TITLE
specify annotation-discrete-coices component

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#210]
the goal is to merge this with #213 if possible
beyond what is described there, the component should:

## Purpose

Let me annotate a generic categorical variable, i.e. one that no vocabulary has been standardized for or where I want to make up my own terms as I go along.

## Use cases

- I just want a data dictionary for this categorical variable, so that I can make a BIDS dataset. So all I want is to write a description for each level of the values. The UI element that displays the description lets me click it and I can now edit the description
  - input
    - value levels (object)
      - keys are column names
      - values are objects with unique column value as the key, and the current description as the value
  - output
    - mapping of unique value to description (columnName, value, description)
- I am willing to map my unique value but I want to enter it myself as a URL (only URL pattern validation)
  - input
    - ...
  - output
    - ...

**Comment by jarmoza** [comment]
There are at least three possibilities that I can think of as to how this component can pick up its discrete choices – and for the annotation page layout to know to use this specialized annotation component:

1. The 'levels' values of the input data dictionary file determines that this component will be used on the annotation page
2. The user explicitly specifies the type of specialized component to be used to annotate the column in question.
3. The app config yaml file allows users to specify which specialized components get assigned to which column.

The latter possibility is one we have only briefly discussed, @surchs. There is the question of where this could occur. If not automatic, the user could select this in the column linking table of the categorization page, or just simply provide a dropdown in the annotation tab itself that swaps out specialized components.
