### ISSUE TITLE
specify annotation-explanation component

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#211]
## Purpose

Show me an explanation text for what I am supposed to do during the annotation workflow of a specific category, so that I can successfully complete the activity.

## Use cases and input / output

- For the category I am currently annotating, display an explanation text to me in the user interface
  - input:
    - explanation text for the current category (plain string?)
  - output:
- I can click a UI element to collapse / hide the explanation so that I have more screen real estate
  - input and also output:
    - the open / closed state of the explanation component for the current category

## Internal state

- we could also have the open/closed state be stored in the component, but then it would reset every time we navigate away and back to the component.

## Ideas

- the open / closed state could also be something we store globally for all explanation components?
- the explanation component could have the ability to scroll if it exceeds a certain size
- we could also have this be a sidebar element in order to save more vertical screen real estate
- the side-bar could slide in from the side or even be a modal

**Comment by jarmoza** [comment]
I think removing this from the vertical space makes a lot of sense.

One other thing we have not yet addressed is just writing the custom text for each annotation tab.
