### ISSUE TITLE
specify annotation-missing-values component

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#212]
## Purpose
For the columns mapped to the category I am currently annotating, show me the unique values that have been declared as missing values, so that I can determine whether they should instead not be missing values.

## Use cases and input / output

-  unique values in columns can be declared as representing "missing" values. for the columns mapped to the category I am currently annotating, show me all values that have been declared "missing". I want to see the value, the column name it belongs to and, if available, a description.
  - input
    - an object with the missing values among columns mapped to the current category under annotation
      - keys are columns
      - values is an array of values for the column that has been declared "missing"
    - a (filtered) data dictionary containing the "levels" attribute for discrete values for the actively mapped columns
      - keys are column names
      - values is the "levels" dictionary where:
        - keys are the value names
        - values are their descriptions (if available)
    - the currently active category (that I am annotating)
- if I want to declare a value to not be missing, I can click on a UI element next to the value (e.g. a button) to remove this value from the missing values
  - input
    - as above
  - output
    - the name of the value to be declared not missing
    - the column that this value belongs to

## Internal State
Component doesn't need internal state

**Comment by jarmoza** [comment]
@surchs 

>a (filtered) data dictionary containing the "levels" attribute for discrete values for the actively mapped columns

To be clear, this is a future idea?

**Comment by surchs** [comment]
No, we already display the description of unique values in the missing values component (if applicable). Currently this comes via a getter method from the store.

**Comment by surchs** [comment]
In order for the component to be able to ask the store for a filtered view of the missing values and their descriptions, it needs to be aware of what filter should be applied. That is, the component needs to know for what category it is being called, e.g.: "I am the missing value component for the `age` category, better go ask the store for all the columns tagged with `age` then...".

How should the component know this?
1. There could be a global app state (kept in the store) of what category is currently being "annotated". It would then switch via the "click on another category tab" action and be read by all components that need to know what category they belong to
2. This could also be a local state in the sense that only the parent component (annotation-tab) is aware of what category is currently shown and then feeds this info to child components via prop

**Comment by jarmoza** [comment]
>This could also be a local state in the sense that only the parent component (annotation-tab) is aware of what category is currently shown and then feeds this info to child components via prop

This is actually being done in the passing of the "title" from the `annot-tab` to the specialized annotation component for that tab. So that tab title could be used as the filter key.
