### ISSUE TITLE
specify upload page (index)

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#214]

**Comment by jarmoza** [comment]
Purpose: Users select the data table and data dictionary files that will be used for annotating

Actions / User flows:
* Select data table (participants.tsv)
* Select data table and cancel selection
* Select data dictionary (participants.json)
* Select data dictionary and cancel selection


Required input:
* Empty data table from store
* Empty data dictionary from store
* Page data from store

Generated output:
* Data table (saved in store)
* Data dictionary (saved in store)

Internal state:
N/A

**Comment by jarmoza** [comment]
Closed by https://github.com/neurobagel/annotation_tool/pull/233
