### ISSUE TITLE
specify categorization page

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#215]
## Purpose

Let me see the columns in my tabular file (and their descriptions if they have them) and allow me to map each to a category from a pre-selected list of categories. 

## Use cases and input / output

OK, this is interesting now. I don't think there is any information that this page actually has to receive or even pass through. It probably just a layout component without any internal logic now. It contains other components that do the work. These components receive their data directly from the state. And all the logic needed to prepare the input for these components (filtering etc) will be implemented inside the store getter methods. So yeah, I think this is just about layout.

What do you think @jarmoza ?

**Comment by jarmoza** [comment]
@surchs Regarding the input, that's a correct assessment. If you look in `categorization.vue`, you can see that it receives its input directly from the store (`mapState`) and provides store values via `provide` and props to its child components.

So if we decide that child components can have access to the store then these mechanisms disappear for the categorization page and its current components.

Method-wise, the page does exist as more than a mere layout, however. It initiates app state via its `mounted` and there are several methods that perform setup for its child components. This can be an interesting rewrite for a cleaner implementation regarding separation of concerns.

**Comment by surchs** [comment]
Ah interesting. Yes, I think now would be a good time to think about the things the categorization page currently does during `mounted`. There are:

- let the store know that "categorization" is now the current page
  - I think this doesn't lead anywhere. Eventually `state.currentPage` gets set in the store, but I don't think this is used.
  - I also think that the desired result of this would be that the nav-bar changes the color of the current page. So the nav-bar component could be where that's handled (and I think it is already)
- make a "columnToCategoryTable" to be shown on the page
  - with the new data flow, this responsibility would fall to the table component
  - the store would need a getter with some reusable data and the component would need to massage into the form it needs for display
- tell the store what the currently selected category is
  - that can also be done by the category-select component via mutation / dispath
- tell the store to initialize the next page (e.g. "annotation").
  - I think this could run in the store / some generic initialization procedure?
  - afaik this is only used for the annotation page initialization. And having this interdependency between pages probably also makes testing harder

**Comment by jarmoza** [comment]
> I think this could run in the store / some generic initialization procedure

Just to point out that the store action `initializePage` is this generic initialization procedure. The current flow is to allow access to the next page of the tool when (one of) the completion states of the current page has been reached, and then page initialization is handled in `mounted` of that next page.

**Comment by jarmoza** [comment]
Since so much is being removed from this page (and I already have a bunch of this work done from my previous refactor work on it), I think another possibility is the entire removal of the next page button from each page and putting it into a footer in the layout template file.

This way 'next page accessible' functionality is relegated to the store (since each check solely depends on values record into the store from user interaction).

**Comment by jarmoza** [comment]
Closed by https://github.com/neurobagel/annotation_tool/pull/233
