### ISSUE TITLE
specify tool-navbar

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#218]
## Purpose

Have a consistent, clickable navigation element at the top of the app so that I can see where I currently am and what pages of the app are accessible based on the actions I have taken so far (app state).

## Use cases and input / output

- display clickable links to each page of the app
  - input
    - page names (object)
      - keys are page names
      - values are (objects) with:
        - index (position)
        - router link (where to go when clicked)
        - accessible (whether you should be able to click through to that page yet)
    - output
      - none (?, I think that's handled by the link itself)

## Internal state

- not needed (?)

## Future ideas
- progress bars or breadcrumb within pages to show more detailed progress / position feedback
- always on top (scrolls with content)

**Comment by jarmoza** [comment]
This refactor will now be concomitant with work being done for the 'next page' refactor work in #232. This is because the state of nav items (color and disabled status) will be dependent on changes being made with the creation of a new `next-page` layout component.

**Comment by jarmoza** [comment]
Closed by https://github.com/neurobagel/annotation_tool/pull/233
