### ISSUE TITLE
define format for annotator config file

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#221]
We want to be able to control the list of categories provided to the user with a configuration file. This file should contain enough information to:

- the name of the category
- preferred colour (:rainbow: )
- know the data type of a category (i.e. categorical, continuous, ...)
- if above isn't enough, also know what type of annotation components to load
- categorization rules (e.g.: there can only be one...)
- contain validation rules for values (if applicable, e.g. controlled term patterns)
- for categorical values: list of permissible values (or API if practical, below)
- (if practical) a reference to an API where a list of allowable controlled terms can be gotten
- human readable explanation to be shown during the annotation workflow

We can start drafting this [here](https://codeshare.io/BA4qmO).

**Comment by jarmoza** [comment]
@surchs *Annotation tool config file?

I believe I am beginning this work on the internal side via the categorization page with the new assessment tool group functionality.

**Comment by surchs** [comment]
Should we keep this thing open @jarmoza? I think configurability is a future goal, but not planned for this round, no?

**Comment by jarmoza** [comment]
@surchs Yes, it's "not planned" for this round but that configurability is coming soon.

Moving to backlog.

**Comment by jarmoza** [comment]
@surchs Agreed with the close as this will inevitably come back up once we move to custom categories, but do you have any further comment on this issue?
