### ISSUE TITLE
Write documentation for component testing

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#223]
We need some docs for ourselves / other developers on how and when to write component tests with cypress. Can start out simple but should have some practical examples for the things we've learned (like the "spy on a mocked mutation" and some of the other complex patterns).

**Comment by jarmoza** [comment]
So far we have two pages addressing this in our documentation repo:

1. [Cypress Vue Testing](https://github.com/neurobagel/documentation/wiki/Cypress-Vue-Testing)
2. [Cypress Test Snippets](https://github.com/neurobagel/documentation/wiki/Cypress-Test-Snippets)
