### ISSUE TITLE
Color selection and storage for custom categories

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#227]
We need to extend our paradigm of one (unique) color for each category for the case when users want to create a new category.

Two potential complementary solutions stand out:

1. A predefined palette is sampled from and checked against for unused colors offering up whatever of the colors in the palette is still available. The limitations of this is the finiteness of the palette. But this can be aided by the use of transparency and opaqueness in the `column-linking-table` to indicate which columns are linked to the currently selected category of the `category-select-table`
2. The addition of a color picker and connected UI element to make it visible for the user selection of the choice of color (This can color choice can also be limited or chosen from a color picker that allows full choice of rgb components.) Something like the color pickers available with [vue-color](https://github.com/xiaokaike/vue-color) - "compact" preferably to limit the palette as described. Sample code of deployment: https://codepen.io/brownsugar/pen/NaGPKy

In addition, it will be useful to save this color choice - no matter how it is selected - for future annotations of the same data set in order to preserve the custom category colors used in the previous annotation run.

**Comment by jarmoza** [comment]
This is linked to upcoming feature #228.

**Comment by surchs** [comment]
@jarmoza I think this is pretty stale. I doubt we'll get to it very soon, and when we do, I believe we will have a different view on what needs to happen. I'd vote to close to keep the issues manageable. wdyt?
