### ISSUE TITLE
Store Refactor (Draft)

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#231]
We're (mostly) done with refactoring individual components. Now we want to find overlap in the getters and mutations that the components expect to access in the store, so that we can reuse these store methods as much as possible. We would like to reuse them so much, that we will consider small refactors of components to allow them to reuse an existing getter/mutation instead of needing a custom one (within reason).

This Epic is a place to track the work and to have some discussion about the overall approach.

- [x] #243
- [x] #247
- [x] #244
- [x] #245
- [x] #246
- [x] #250

Codeshare for our original I/O store refactor spec'ing: https://codeshare.io/r9WllY

**Comment by jarmoza** [comment]
**Store Changes:**

1. new store getter `columns`, a list of objects that contain a column `name` and column `description` (empty string if none) parsed from the `dataTable` and `dataDictionary`

In order to produce the table rows of the `column-linking-table`, a function located in the categorization page `setupColumnToCategoryTable` was run and its return value passed to the `column-linking-table` as prop.

Instead, the refactored `column-linking-table` now utilizes a new store getters `columns` (which parses this information, name and description of each column from the `dataTable` and `dataDictionary` store fields)

```
            setupColumnToCategoryTable() {

                // 0. Check that there is at least a data table and data dictionary in the data store
                if ( null === this.dataTable.original )
                    return;

                // 1. Produce an array of dicts
                this.columnToCategoryTable = [];

                // A. Each dict has a header entry from the data table file
                const headerFields = [];
                for ( const headerField in this.dataTable.original[0] ) {

                    // I. Save the header field in a list
                    headerFields.push(headerField);

                    // II. Save a new dict for this column and description
                    this.columnToCategoryTable.push({

                        "category": null,
                        "column": headerField,
                        "description": ""
                    });
                }

                // 2. Add in descriptions if a data dictionary has been supplied
                if ( null !== this.dataDictionary.original ) {

                    // A. and a corresponding "description" column that is (possibly) sourced from the json file
                    for ( const column in this.dataDictionary.original ) {

                        // I. Save a lowercase version of the current json key
                        const columnLowercase = column.toLowerCase();

                        // II. Try to match the json key with one in the tsv file
                        if ( headerFields.includes(columnLowercase) ) {

                            for ( let index = 0; index < this.columnToCategoryTable.length; index++ ) {

                                // NOTE: Advanced column name matching here between tsv and json? J. Armoza 01/26/22
                                if ( columnLowercase === this.columnToCategoryTable[index].column.toLowerCase() ) {

                                    // a. Determine the description string for this json file column entry
                                    let descriptionStr = "";
                                    for ( const subkey in this.dataDictionary.original[column] ) {

                                        if ( "description" === subkey.toLowerCase() ) {
                                            descriptionStr = this.dataDictionary.original[column][subkey];
                                            break;
                                        }
                                    }

                                    // b. Save the description from the json file colum entry
                                    this.columnToCategoryTable[index].description = descriptionStr;
                                }
                            }
                        }
                    }
                }
            },
```

**Comment by jarmoza** [comment]
The functions below were removed from the categorization page relating to the `categ-tool-group` component. Depending on what we end up doing with that component and its functionality, these functions may be need to moved to the store and/or altered.

```
            removeToolGroup(p_toolGroupData) {

                // Remove this tool group from the store
                this.$store.dispatch("removeToolGroup", p_toolGroupData);
            },

            saveNewToolGroup(p_toolGroupData) {

                // Create this new tool group in the store
                this.$store.dispatch("createToolGroup", p_toolGroupData);
            },

            setSelectedCategory(p_clickData) {

                // Save the name of the selected category
                this.selectedCategory = p_clickData.category;
            },

            toolGroupAction(p_event) {

                // Create, modify, or remove this tool group in the store
                this.$store.dispatch(p_event.action, p_event.data);
            }
```

**Comment by surchs** [comment]
Hey @jarmoza and @rmanaem: we have our sketch of the store refactor from [the miro board](https://miro.com/app/board/uXjVP8wIUms=/?share_link_id=605767546623). Now we should implement what's on the board as state variables, mutations, and getters in the store. Ideally we can do this in very small and easy to understand increments, maybe even one mutation/getter/action/variable at a time. 

One problem will be (I think) that the end-to-end tests will continue failing until we have successfully stitched everything back together. That's a bit too wobbly for my taste - if a mutation is bugged, we'd ideally catch that right away. One answer is to use unit tests for the store methods (see #250) - and I think we should do that. Another (parallel) idea might be to figure out partial e2e tests that might already work even though the rest of the app is still broken (e.g. getting up to the categorization page, even though annotation is still broken). @jarmoza: any idea how feasible this might be?

Let's collect some thoughts here on:
- how to break up the work on the miro board into (ideally) independent chunks
- how to assure that new / refactored code works, even though the whole app is still broken (testing)

and then discuss
