### ISSUE TITLE
Next Page Accessibility moves to layout/store

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#232]
We are now going to remove the checking of app state from the individual pages and split the responsibility of doing so between the default layout of the app and store values/methods.

The next page button depends on the state of the app and whether or not the conditions to proceed to the next page from the current page have been met via user interactions within the current page.

My current idea is to implement the following:

- [ ] Move page accessibility criteria to a `pageAccessible` (and wrapper `nextPageAccessible`) function in the store that returns a boolean value based on whether or not the condition logic for `currentPage` is currently met. The output of this function will flag the disabled status and color of the next page button on each page.
- [ ] The next page button will sit on the lower right of each page in a footer-like row.
- [ ] Button text and instructions text (if it exists for the current page) will all be stored in the data of this new next page component.
- [ ] Adjust code for the annotation tool's navbar to reflect these internal changes

As such, this work touches each page, the default layout and the store.

**Comment by jarmoza** [comment]
Because this refactor necessarily affects the enabled status of nav items in the tool's navbar #218 is linked to this issue.

**Comment by surchs** [comment]
I think this makes sense to me @jarmoza. So this new next button would become part of the layout and receive the active page name in the same way the current `tool-navbar` does?  And then both the `next-button` and the `tool-navbar` component outsource the responsibility of determining whether a page is accessible to a store getter? 

I think that's really clean. Then these two components are only responsible for styling their UI correctly in response to the store changing the status of a page, but the only source of truth about page status is handled by the store.

**Comment by jarmoza** [comment]
Closed by https://github.com/neurobagel/annotation_tool/pull/242
