### ISSUE TITLE
Hitting "Save" during annotation should give a visual confirmation to the user

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#234]
As a user, when I click the "save" button during annotation, I want to get a visual confirmation that the data made it successfully to the store / is stored.

This could be a [simple toast](https://bootstrap-vue.org/docs/components/toast) or something nice like that. For the user it might even be enough if the visual element is triggered by the button and not by some actual check that everything successfully made it to the store.

**Comment by jarmoza** [comment]
@surchs Since this is so recently opened, did you have any ideas on the form of visual confirmation?

**Comment by surchs** [comment]
Yeah, thanks, this should have gotten a description. I'll add my initial idea and then remove the label!

**Comment by rmanaem** [comment]
I think so since the save annotation button has been removed. However, we may need another way to hint/show the user that their annotation has been saved. I'd say close this and rely on the feedback from users.
