### ISSUE TITLE
During data categorization, it would be helpful to have a preview of the data in each column

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#235]

**Comment by jarmoza** [comment]
@surchs Also another newly-proposed feature. Should this be put to backlog along with #234?

**Comment by surchs** [comment]
Hhm, I'm not sure. This one feels a little more remote to me at the moment. I would also be OK with just closing it and waiting for it to become a problem. wdyt @jarmoza

**Comment by jarmoza** [comment]
> I would also be OK with just closing it and waiting for it to become a problem.

I agree.
