### ISSUE TITLE
Lets get the task names from Cognitive Atlas

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#238]
We want a list of task names that we can offer to our users as values for cognitive tasks. There is this project to harmonize task tames run by Valentina: https://docs.google.com/spreadsheets/d/1_f6M5ompblVKOxYbRQLmEi4PMHtFO40J/edit#gid=97866687

We should make a list of things to do for this. One of them is probably to see what the CogAtlas API has to offer us in terms of metadata: https://cognitiveatlas.org/api/task

**Comment by jarmoza** [comment]
@surchs Any thoughts as to what release to put this into?

**Comment by surchs** [comment]
I think this could go in with the (re-) addition of assessment tool annotation in (one of) the next release.

**Comment by jarmoza** [comment]
Noted for Milestone Cycle 4 (March)
