### ISSUE TITLE
Draft the getters / mutations needed by the file-upload page

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#245]
Closely related to https://github.com/neurobagel/annotation_tool/issues/203. Implementation depends on whether we want the page to talk to the store or if the components can do it.

**Comment by surchs** [comment]
@jarmoza: would you say that we have all the getters / mutations that we will need to have the file-upload page run? If so, feel free to close this!

**Comment by jarmoza** [comment]
@surchs This can now be closed. I've moved the `saveDataTable` and `saveDataDictionary` to the file/upload page in our [Miro diagram](https://miro.com/app/board/uXjVP8wIUms=/).
