### ISSUE TITLE
Define unique getters and mutations

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#247]
Some components need a getter / mutation that is very specific and isn't used by anyone else (for now). We haven't defined these yet on [the miro board](https://miro.com/app/board/uXjVP8wIUms=/?share_link_id=605767546623). To prepare for #244, we should also add these unique getters / mutations to the board (and link them with their unique components).

**Comment by surchs** [comment]
I think this is also done on the miro board. @rmanaem, could you check, and if you agree close?

**Comment by jarmoza** [comment]
This is not done as of yet. I'm going to grab this will mark when it's finished.

**Comment by surchs** [comment]
could you look at this and #245 and see if we can close this? I think you added all the ones we know of in #251
