### ISSUE TITLE
Refactoring the store to use the data dictionary: Phase 1

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#251]
This Epic tracks progress on implementing the required store methods (getters, actions, mutations, etc) to complete the ongoing store refactor. 

We will do this in two phases: 
1. Addressing all changes required by components on the index and categorization page. Once complete, we will confirm success by creating / running an integration test across the two pages (this issue)
2. Addressing all remaining changes. Once complete, we will confirm success by running additional integration and complete end to end tests (#305)

## Resources:

[Here is a great blog post](https://dev.to/bahmutov/unit-testing-vuex-data-store-using-cypress-io-test-runner-3g4n) by one of the cypress maintainers on how to unit-test, mock, stub, etc Vuex methods. 

There are also some examples for these unit tests in our wiki now: https://github.com/neurobagel/documentation/wiki/Cypress-Test-Snippets

## Completion checklist

Every implemented method should have:

1. the method implemented in the correct section (getter, mutation, ...) in the store
2. all necessary state variables that the method relies on are initialized in the state (i.e. defined, not assigned real data) 
3. unit test(s) that test the core functionality of the method (required state variables in the store and any other needed inputs should be mocked)
4. any component that depends on this method existing ([check miro board](https://miro.com/app/board/uXjVP8wIUms=/?share_link_id=577947271587) and codebase) is checked to make sure it is calling the new method by the correct name and is refactored (including its component tests) where necessary to do so

# Phase 1 - up to Categorization page

- [x] #259 
- [x] #252
- [x] #265
- [x] #253
- [x] #281
- [x] #254
- [x] #255
- [x] #260
- [x] #261
- [x] #256
- [x] #257
- [x] #300
- [x] #324
- [x] #306
- [x] #322 
- [x] #307

With that done, to wrap up we need to do

- [x] #308
- [x] #309
- [x] #310
- [x] #311
- [x] #313
- [x] #314
- [x] #315

This phase will be done when

- our app launches
- e2e page tests for index and categorization pass (with some adjustments)

**Comment by jarmoza** [comment]
Here's a list of the actions/getters/mutations currently listed in our [Miro diagram](https://miro.com/app/board/uXjVP8wIUms=/):

**actions:**

revertColumnToOriginal
saveDataDictionary
saveDataTable

**getters:**

getActiveHeuristic
getAnnotationComponent
getCategories
getColumns
getDataDictionary
getDescription
getExplanation
getHarmonizedPreview
getMappedColumns
getOptions
getUniqueValues
missingValues
nextPage
pageAccessible

**mutations:**

alterColumnCategoryRelation
changeMissingStatus
createColumnToCategoryMap
selectAnOption
setCurrentPage
setHeuristic
setupAnnotationDetails
setupCategories

**Comment by jarmoza** [comment]
Linking discussion from [UI should always reflect internal annotation state](https://github.com/neurobagel/annotation_tool/issues/128) as our refactor of the store will move us toward being able to better keep track of annotations being made to the original data table/data dictionary.

Likely we will want to spin off a subtask for the UI portions of this enhancement.
