### ISSUE TITLE
create mutation to change column to category mapping

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#252]
When called with arguments for a `column` and a `category`, this mutation should change the link between a `column` and a `category` in the following ways:

- [x] if the `column` and `category` are already "linked", the `column` should be "unlinked" from this `category`, i.e. set to a default value indicating "no link"
- [x] else: if the `column` is not yet linked to any category OR is linked to a different category than `category`, the `column` should now be linked to `category`

Other requirements:

- [x] depending components have been checked and are calling this mutation correctly
- [x] depending component tests have been checked and are calling this mutation correctly
- [x] have unit tests to check functionality
- [x] needed store state variables exist already or have been created if not

**Comment by rmanaem** [comment]
@surchs @jarmoza
Is there a way to somehow directly reference the p_row e.g., 

`@row-clicked="alterColumnCategoryMapping(activeCategory, p_row.column)"` 

here in `<b-table>`

https://github.com/neurobagel/annotation_tool/blob/9086057555dfc9cadf91bc88589925be3b148bcf/components/column-linking-table.vue#L5-L16

instead of inside `applyCategory`

https://github.com/neurobagel/annotation_tool/blob/9086057555dfc9cadf91bc88589925be3b148bcf/components/column-linking-table.vue#L78-L86

**Comment by surchs** [comment]
I think you should have access to the same event payload that the `applyCategory` method is consuming - I believe if you don't specify anything, then the entire event object is passed by the event (`@row-clicked`) to the event handler (`applyCategory`). That said, I would check out the docs of the component library (vue-bootstrap) for details on the `b-table` component: https://bootstrap-vue.org/docs/components/table#data-row-accessibility

**Comment by rmanaem** [comment]
I briefly looked through the docs yesterday. The closest implementation to what I had in mind is this:

`@row-clicked="(p_row, p_index, p_event) => alterColumnCategoryMapping(activeCategory, p_row.column)"`

**Comment by surchs** [comment]
that doesn't look super readable to me. Any particular reason you want to avoid the method call and handle committing the mutation from there?

**Comment by rmanaem** [comment]
I was thinking we can remove applyCategory so less code &rarr; cleaner

**Comment by surchs** [comment]
I see. OK, I see that point. Makes it more explicit that the event is directly passed to the mutation. Let's see what it looks like in the component
