### ISSUE TITLE
create action to save the uploaded dataDictionary to the store

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#257]
Now that we have said in #256 that loading a new dataTable signals that the app should be completely wiped, this action should expect that a dataTable has already been loaded and there already is a skeleton dataDictionary in the store. 

So the goal here would be: 
- take the uploaded data dictionary
- see what keys already exist in the state.dataDictionary 
- augment existing keys without (ideally) overwriting any already existing content
- ignore all keys that only exist in the uploaded data dictionary but not in the state.dataDictionary
  - whenever a new dataTable is uploaded (e.g. #256), the app state is wiped and re-initialized
  - as part of this, the `state.dataDictionary.annotated` is also re-initialized
  - it will be a skeleton data dictionary that only contains the keys for each column in the `dataTable`, and some barebones attributes to contain future annotations
  - so when a user adds an already created data dictionary, it should get merged into the skeleton data dictionary that was created during `dataTable` upload
  - because we know that the skeleton data dictionary will contain keys for every column in the `dataTable`, if the user supplied data dictionary has additional keys, then they must be faulty or otherwise mismatched
  - in such a case, we should not add them to the data dictionary and we could tell the user that we ignore these keys

**Comment by surchs** [comment]
@rmanaem want to take a look at this?

**Comment by surchs** [comment]
@jarmoza: I updated the general points up there, let me know what you think.

**Comment by jarmoza** [comment]
@surchs Can you explain this use case a bit more so I can understand why we should be ignoring parts of newly uploaded data?

> ignore all keys that only exist in the uploaded data dictionary but not in the state.dataDictionary

**Comment by jarmoza** [comment]
>augment existing keys without (ideally) overwriting any already existing content

@surchs Can you further explain what this sentence means, particularly the word 'augment', here? I need clarification.

**Comment by surchs** [comment]
> augment existing keys without (ideally) overwriting any already existing content

Hey @jarmoza. I think we can drop this requirement. My original idea was: if the user starts with just the table uploaded, that creates a skeleton data dictionary (so annotation can commence). If the user then does a bit of annotation but then decides to come back and upload an existing data dictionary (because they forgot), this data dictionary should be merged with the skeleton data dictionary so none of the already made annotations are lost. 

I now think this is overcomplicated and not required. So what we should do instead is:

1. if the user uploads a dataTable (and app state gets wiped), a skeleton data dictionary is made so annotation can commence
2. if the user then decides to also upload an existing data dictionary, the definitions in the uploaded datadictionary should replace the ones in the skeleton dictionary.


> ignore all keys that only exist in the uploaded data dictionary but not in the state.dataDictionary

This requirement means that when the user uploads an existing data dictionary that for some reason has definitions for columns that are not in the currently loaded dataTable, then these columns should be ignored 

e.g.:

```javascript
skeleton_dict = {
  col1: "something",
  col2: "other"
}

user_dict = {
  col1: "something else"
  col3: "ups, wrong column"
}

// Then
merged_dict = {
  col1: "something else",
  col2: "other"
}
```

**Comment by jarmoza** [comment]
Perfect! That's clear now. Thanks @surchs.
