### ISSUE TITLE
create mutation to initialize category style data structures

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#262]

**Comment by surchs** [comment]
@jarmoza: based on what we discussed, can this mutation be replaced by directly setting the `colorInfo` or something like it with the desired default values on the `store.state` object? I don't think we have any way for the user to change either the colors or their mapping to the categories - so it would be functionally the same.

**Comment by jarmoza** [comment]
@surchs If part of the intent of the refactor is to have consistent initialization of store fields then yes, these values can be hardcoded in the state object definition.

That said, the `setupCategories` function logic is written to accommodate future custom palette functionality.

**Comment by surchs** [comment]
@jarmoza I copied the current implementation into #282 for reference. I think we can close this issue now.
