### ISSUE TITLE
create mutation to initialize annotation component details (one per category)

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#263]

**Comment by surchs** [comment]
@jarmoza, like in #262 could this mutation be replaced by directly setting the defaults for the `annotationDetails` object (or something similar) in the `store.state` object? I don't think the user can so far provide any information that would change what this gets initialized to, so it would be functionally identical.

**Comment by jarmoza** [comment]
The scenario where a user could provide input for such a function: when a user can specify  the data type of a custom category they wish to have built into the annotation tool.

In other words, this would be for a future dynamic feature. `annotationDetails` - or whatever it is called in the refactor - can be initialized in the store object definition as you say in the interim.

**Comment by surchs** [comment]
Yes, understand. This makes sense for a future feature implementation. @jarmoza is there some piece of code you want to track in a new issue for when this may be implemented? If yes, could you create the new issue, paste the code and a short note on what it might be useful for, link it here, and then close this issue?

**Comment by jarmoza** [comment]
@surchs Yes, I'll create an issue to note the desired functionality with some (pseudo)code.

**Comment by jarmoza** [comment]
@surchs I've created a new issue for this feature here: https://github.com/neurobagel/annotation_tool/issues/286
