### ISSUE TITLE
create getter for preview of value after heuristic transformation

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#272]
Implement a getter, `getHarmonizedPreview`, that returns a version of the original value as transformed by the currently selected transformation heuristic for a category ([soon to be column](https://github.com/neurobagel/annotation_tool/issues/336)).

- [x] depending components have been checked and are calling this mutation correctly
- [x] have unit tests to check functionality
- [x] needed store state variables exist already or have been created if not

**Comment by jarmoza** [comment]
@surchs I think we should have a discussion here in this issue and/or by video regarding the different transform heuristics we have in regard to their implementation pre-refactor – and how we might want to change them.

**Comment by surchs** [comment]
ok, happy to discuss here! Do you want to start by explaining what you'd like to change?

**Comment by jarmoza** [comment]
Closed by #368
