### ISSUE TITLE
create getter for value options of a column (categorical or continuous)

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#276]
Implement a getter that provides options for categorical column or transform heuristic options for a continuous values column.

Other requirements:

- [x] depending components have been checked and are calling this mutation correctly
- [x] have unit tests to check functionality
- [x] needed store state variables exist already or have been created if not

**Comment by surchs** [comment]
Note: on the miro board, this getter is supposed to be called `getOptions` - this will likely need some refacvtoring of the affected components that are currently calling it under a different name

**Comment by jarmoza** [comment]
@surchs Is this our current list of transform heuristics for continuous values?

`["float", "bounded", "euro", "range", "int", "string", "isoyear"]`
 
This is taken from the component test for `annot-continuous-values` and the old `convertAge` in `annot-age-values`

**Comment by surchs** [comment]
Yes @jarmoza, that's what we have been calling them. That said: these were the names of the regex capture groups, if you think of more descriptive names, feel free to use (and document) those instead!

**Comment by surchs** [comment]
@jarmoza is this Blocked or Fixed? Looks like #352 took care of it?

**Comment by jarmoza** [comment]
No, though I'm guessing you meant another issue @surchs?

In any case, this had been marked as blocked pending discussion but I am ready to move on to this task next now that I've just finished up with missing values tasks.
