### ISSUE TITLE
How can we make sure every component test gets a fresh mocked vuex store

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#288]
To mock the vuex store in component tests, at the moment we define the mocked store object before any test is run, and then pass the same reference to the `cy.mount` command of each test in sequence, e.g. 
https://github.com/neurobagel/annotation_tool/blob/86bf385d98aad17b042a17d9d2efe6a5c33d48dd/cypress/component/column-linking-table.cy.js#L93-L105

I just encountered a problem where running two tests that pass individually (e.g. via `it.only`) in sequence fails the second test. The specific problem for me was that I was trying to wrap a function on the mocked `store` object in a `cy.spy` wrapper like so
https://github.com/neurobagel/annotation_tool/blob/86bf385d98aad17b042a17d9d2efe6a5c33d48dd/cypress/component/column-linking-table.cy.js#L92
but if the test was run after a previous test, this failed with `Attempted to wrap undefined property commit as function`

I was able to resolve this specific problem by wrapping the entire mocked store object in a `beforeEach` statement so that each test should get the same `store` object and possible changes don't persist.

But I am not sure that this is the correct way to ensure that there is no interdependence between our tests. The [vuex docs on testing](https://vuex.vuejs.org/guide/testing.html) are a bit sparse, but they seem to use a factoryMethod to create a new store for every test. I am not sure what that would look like for our tests, but I think we should take a look at it and then decide whether we should also use a factoryMethod. See also our [vue-test-utils guide](https://v1.test-utils.vuejs.org/guides/using-with-vuex.html).

**Comment by jarmoza** [comment]
So something like this?

```
function generateStore() { return { ... }; }

cy.mount(ColumnLinkingTable, { 
  
     mocks: { 
  
         $store: generateStore() 
     }, 
     ....
});
```

**Comment by surchs** [comment]
Interesting. Yeah, maybe like that! I think one of the nice things about a store factory method would also be that it is a quick way to get a fresh store with the default initialized state values whenever you need it. 

I am still not completely clear how you would continue mocking things inside of a component test then. Call the factory method to make a fresh store object. And then manually write to state objects (close to what we already have) or run some fancy script to call mutations to make the store look like what you want (close to what we had in the past)? 

I think it would be very nice to see or ask  how others are doing this and then decide whether we also want to copy that here.

**Comment by jarmoza** [comment]
@surchs It seems that one common practice is to instantiate a `Vuex.Store` object and load up getters, mutations, etc into it for use in calls to `mount` (sort of as we have done) or `shallow` (I'm guessing this is the equivalent of `shallowMount` in vue-test-utils). This is done in both end to end and component testing in the below example pages.

- [Testing Vue web applications with Vuex data store & REST backend](https://www.cypress.io/blog/2017/11/28/testing-vue-web-application-with-vuex-data-store-and-rest-backend/)
- [Mocking Vuex in Vue unit tests](https://medium.com/@lachlanmiller_52885/mocking-vuex-in-vue-unit-tests-b6eda1c4d301)
