### ISSUE TITLE
bump cypress version

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#293]
our cypress version is quite behind. For example, component testing has come out of beta last month: https://www.cypress.io/blog/2022/12/15/cypress-component-testing-for-developers/

We should update the cypress version. This is true for other packages as well, but we can track that problem somewhere else.

**Comment by jarmoza** [comment]
@surchs and I discussed this issue yesterday, coincidentally. This will be addressed after the store refactor. So "Milestone 4" - likely in late February/early March.
