### ISSUE TITLE
remove old tool-group functionality from the categorization page

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#306]
For this first release we will remove the annotation-tool-group workflow again. It will be re-implemented using a different UI. To make sure our tests still pass, we need to remove the functionality for annotation-tool-group markup in the categorization and annotation components.

**Comment by jarmoza** [comment]
Old tool group functionality was removed in https://github.com/neurobagel/annotation_tool/pull/233/commits/75cff0e6505073a31d345078b4b7f668ab45ed9c
