### ISSUE TITLE
refactor page test setup

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#309]
Our page e2e tests rely on some cypress support functions to run (e.g. [here](https://github.com/neurobagel/annotation_tool/blob/dev_components_talk_to_store_directly/cypress/e2e/page/categorization-pagetests.cy.js#L15)). These functions need to be refactored to make use of the new store methods (updated actions, mutations). The goal is that the page tests run (not necessarily pass).

**Comment by jarmoza** [comment]
Closed by #330
