### ISSUE TITLE
Adapt data dictionary and data table upload/store functionality for refactor on Index page

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#314]
Code for the data dictionary found in `index.js` and `index.vue` now needs to be connected for the initial refactor work and to align with how the data table is set loaded – specifically that the data table must be uploaded first before data dictionary upload is allowed.

*Store*
- [ ] `processDataDictionary` action now calls mutation `setDataDictionary` with an object as payload containing the new data dictionary and the current data table's column names

*Index.vue*
- [ ] `processDataTable` and `processDataDictionary` actions are now called directly after a `file-selector` component emits that a file has been selected
- [ ] The file selector component for the data dictionary is now disabled until a data table has been chosen (new `file-selector` prop `enabled` is tied to the length of the data table in the store. See `dataTableSelected` computed value.)

*file-selector.vue*
- [ ] Ability to be disabled by parent (This stems from the need for a data dictionary not to be uploaded before a data table is first uploaded on the index page.) New CSS class `disabled-file-selector-button` has been added for this purpose and is swapped out via the new `labelClass` computed value.

**Comment by surchs** [comment]
> Store

>    processDataDictionary action now calls mutation setDataDictionary with an object as payload containing the new data dictionary and the current data table's column names

> Index.vue

>    processDataTable and processDataDictionary actions are now called directly after a file-selector component emits that a file has been selected

> The file selector component for the data dictionary is now disabled until a data table has been chosen (new file-selector prop enabled is tied to the length of the data table in the store. See dataTableSelected computed value.)

@jarmoza: I think all of these are already addressed in previous PRs. I believe the only new functionality here is disallowing a data-Dictionary upload before a dataTable has been uploaded. I think we should change the issue title and description to focus on the new functionality

**Comment by jarmoza** [comment]
Closed by #329
