### ISSUE TITLE
Adapt navbar/next button and page accessibility status for initial refactor work

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#315]
With the removal of the explicit changing of page accessibility in the pages (via the`accessible` flag in the store `pageData` field), the navbar now must itself keep watch of the store state for updating the active status and colors of its nav items.

*Store* 
- [ ] A new action `updatePageDataAccessibility` is called as necessary to update whether or not the store state has changed as to allow for access to the various pages of the annotation tool
- [ ] A new mutation `setPageAccessible` alters the `accessible` flag for the appropriate page in `pageData` (via `updatePageDataAccessibility`)

*tool-navbar.vue*
- [ ] Page accessibility is rechecked via its `updated` hook

**Comment by surchs** [comment]
@jarmoza: As we had discussed yesterday, we can just re-use the existing `isPageAccessible` getter in the `next page button` and also in the `nav-bar`

**Comment by jarmoza** [comment]
Closed by #328
