### ISSUE TITLE
Refactoring annotation, download, and simple e2e tests

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#333]
Now that I am working on the second phase of our store refactor, I am beginning with understanding what is broken in the current e2e tests for the annotation and download pages - potentially the 'simple' (full app) e2e test.

This may not be fully completable until the end of the second phase of the refactor.

Linked to #332

**Comment by rmanaem** [comment]
Blocked by #400 as the simple e2e test requires download page button to be accessible.

**Comment by jarmoza** [comment]
Closed by #405
