### ISSUE TITLE
[ENH] Ability to select annotation tab type for (categorized) column

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#334]
In the column linking table, it will be useful to have a drop down per column where users can select the data type of the column (and thus the specialized component type that will be used on the annotation page tab for this column. This is particularly the case for custom categories introduced by the user via the `category-select-table`.

@surchs Let's begin a discussion here about this feature. For the time being, annotation tabs will be hardcoded as `annot-continuous-values` for 'Age' and `annot-categorical` for 'Sex' and 'Diagnosis'.

**Comment by surchs** [comment]
@jarmoza: I think what we have discussed now is that the type of component will be defined as part of the category. E.g.: for the category of "sex", a categorical component will be used. So if users can (in the future) define their own categories, they would also have define what component should be used. I think this would then make an additional selection of the component/data-type by the user unnecessary. Wdyt?

**Comment by surchs** [comment]
cognitive assessments are what we previously called "tool groups": a bunch of columns that belong to the same test - and we want to know what subjects have completed the test successfully.

**Comment by jarmoza** [comment]
Tied to #282
