### ISSUE TITLE
Feature: Ability to choose different transform heuristics for columns in continuous values component

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#336]
We want to allow users to select different types of data transformation heuristics (from those available) for the columns of a continuous values category (i.e. 'Age').

1. UI changes must be made in the in `annot-continuous-values` component for this to occur. The suggested solution is a multi-tabbed continuous values component where each tab represents a column and where within each tab there is a dropdown for the column's transform heuristic – somewhat similar to the current implementation that selects a heuristic for all columns.
2. Once the choice is made a mutation must be written to alter the annotated data dictionary to register the newly selected heuristic for its respective column.

Tied with #270 and #274

**Comment by jarmoza** [comment]
@surchs Does this sound about right to you?

**Comment by surchs** [comment]
Makes sense to me @jarmoza. What I would add is that both the "user-selected-a-heuristic-for-this-column-please-store" mutation and the "what-heuristic-is-currently-stored-for-this-column" getter have to be updated for this to work. And, as we discussed: the choice of available heuristics (i.e. a list of possible string names of heuristics the user can choose from) is still going to be tied to the category.

**Comment by surchs** [comment]
@jarmoza can we close this?

**Comment by jarmoza** [comment]
@surchs No, this is the new feature that will be my upcoming PR.

**Comment by jarmoza** [comment]
Closed by #372
