### ISSUE TITLE
Diagnosis annotations wiped when saved twice

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#339]
As noted in #335, when saving Diagnosis annotations twice (via the 'Save Annotation' button on the Annotation page), Diagnosis columns in the table on the Download page appear completely clear of data.

![image](https://user-images.githubusercontent.com/4140162/216369158-3e43fdd9-b3a7-4aa8-b297-975a75d6687a.png)

This is similar to our previous bug #176  for categorical annotations (e.g. Sex)

**Comment by surchs** [comment]
@jarmoza @rmanaem: could you see if this can be closed directly?

**Comment by rmanaem** [comment]
I think so since both the save annotation button and the table have been removed.
