### ISSUE TITLE
Remove old store file post-refactor

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#344]
During the refactor I wanted the old store version to stick around as an example in case we missed something during our design of the new store.

Once the store refactor is done (ostensibly with Phase 2), the previous store, now named `index-old.js` should be removed from the repo.

**Comment by surchs** [comment]
@jarmoza: is this blocked? If so, could you move it to "tracked" in the new status?

**Comment by jarmoza** [comment]
This is "Next", so I marked it as "Specify - Done".

**Comment by jarmoza** [comment]
Closed by #383
