### ISSUE TITLE
columnToCategoryMapping vs dataDictionary.annotated.<column>.mappedToCategory

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#358]
In our [store refactor Miro board](https://miro.com/app/board/uXjVP8wIUms=/), we have two means of indicating that a column is linked to a category. The first is the `columnToCategoryMapping` store field, and the second is a field `mappedToCategory` that sits within the column definition in `dataDictionary.annotated.<column>.mappedToCategory`.

The question is if the latter field should be removed from the data dictionary spec or if the categorization page (and annotation page) should adding/subtracting the value for the `mappedToCategory` field in addition to touching the `columnToCategoryMapping` store field.

My sense is we should remove `mappedToCategory` and use `columnToCategoryMapping` as the source of truth. But I do not recall the reason why this field was placed in the data dictionary.

@surchs or @rmanaem  Do you recall why it's there?

**Comment by surchs** [comment]
I think the original idea was that the `dataDictionary` contains all of the relevant information, and that we could have secondary "convenience" variables (like `columnToCategoryMapping`) that get generated based on the data dictionary. So in hindsight the idea was probably to have `columnToCategoryMapping` be a getter. 

That said: we have already implemented `columnToCategoryMapping` as a store variable like you suggest to continue doing - and I don't think there are any problems with that approach. So I agree: now that `columnToCategoryMapping` is its own store variable, the (not yet implemented) `mappedToCategory attribute in the data dictionary is no longer needed and should not be implemented.

**Comment by jarmoza** [comment]
@surchs So the idea is that we want the category information in the output from the download page?

If so, I will make a note of that on the refactor issue for that task.

Looking through the codebase, it appears that legacy is not the only (good) reason for retaining `columnToCategoryMapping`. This object is used many times as a quick way of determining category for a column, and particularly within store getters. If it did not exist, we would have to generate this mapping multiple times within the getters for which it is used.

**Comment by surchs** [comment]
> So the idea is that we want the category information in the output from the download page

yes

>  (good) reason for retaining columnToCategoryMapping

agreed. to be clear: I'm in favour of keeping `columnToCategoryMapping` around

when we get to the download page and creating the desired output we can worry about how we add this information to the output.

**Comment by jarmoza** [comment]
I've added a note about this in #268
