### ISSUE TITLE
Refactor controlled terms in the store

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#371]
Right now, we're handling controlled terms for discrete categories (e.g. "sex", "diagnosis") as simple strings - specifically as human comprehensible labels. However, a controlled term needs an IRI / identifier, and can also have a human label. Like so:

```json
{
"identifier": "https://neurobagel.org/vocab/myControlledTerm",
"label": "My specific term"
}
```
instead of `myTerm = "My specific term"`

Mid-term, we will need to treat controlled terms as objects with identifier+label. In the short term, we can decide whether we handle them as simple strings in the app, and then only turn them into objects with identifiers at the end, when we create the data dictionary to download.

## Affected parts of the annotator
Here is what I can see would be impacted by a complete refactor:

- store
  - state
    - categoricalOptions
  - getters
    - getCategoricalOptions (should now return both label and identifier?)
  - mutations
    - selectCategoricalOption
    - ~~setHeuristic~~
- components
  - annot-categorical
    - expects categorical choices to be a list of strings, but would have to now handle objects with identifier + label
    - fires `selectCategoricalOption` mutation and passes the string-label of the controlled term, but would now also have to pass an identifier to make this unambiguous

To a lesser extent, this would also be a concern for the annot-continuous workflow where a transformation heuristic could (should ?) have an identifier in the future.

I think it makes sense to deal with this now, the required changes shouldn't be very extensive. Here's a list of things that need to happen:

- [x] change `state.categoricalOptions` to be an array of objects with `label` and `identifier` each, hard-coded in the store
- [x] update components using `getters.getCategoricalOptions` to handle 1) objects with `label` and `identifier` instead of the current string, 2) handle empty arrays
- [x] update components using `mutations.selectCategoricalOption` to handle objects being passed around now instead of strings.

**Comment by rmanaem** [comment]
@surchs I'm a little unclear about the timelines you mentioned. what do you mean by short-term (while we're in the refactoring phase of annotation tool?) and mid-term (after the refactoring is done or when we have a mechanism for uploading data to the graph)? 
what do you mean by refactoring now (as part of phase 2) and later (after phase 2 or some other time)?

**Comment by surchs** [comment]
Thanks for the question @rmanaem! You're right, wasn't clear: to me

- short term: right now as part of Phase 2 refactor
- mid term: immediately after phase 2 refactor (possibly mixed in with the next round of features)

**Comment by surchs** [comment]
Also decided not to work on the handling of the continuous value transformation heuristics now, because there is a much lower need to be explicit about the identifiers / handle them separately from the label we show the user.
