### ISSUE TITLE
Find better naming for the pages

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#38]
Loading, Categorization, Annotation, and Download are not very intuitive. We should come up with more descriptive page names.

Some ideas:
- look at the BIDS specs for what these things are called

**Comment by surchs** [comment]
I will keep this open but unless we get feedback about the pages being named confusingly, I don't think this should be a priority.

**Comment by jarmoza** [comment]
Since we were just on the topic of page names, can this be closed? Did you have more intuitive page name ideas other than "Categorization, Annotation, and Download"? (We are currently not using "Loading" for the home/index page.)
