### ISSUE TITLE
BUG: Descriptions not showing in column linking table yet component test passing

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#384]
In our [current dev branch](https://github.com/neurobagel/annotation_tool/tree/dev_components_talk_to_store_directly), the descriptions for columns from the data dictionary file are not visible in the 'description' column of the `column-linking-table` component.

Additionally, the component test for `column-linking-table` is passing meaning the test is not as robust as it should be. For this bug fix:

- [x] Descriptions from the data dictionary should be showing up in the 'description' column of the `column-linking-table`
- [ ] The component test for the `column-linking-table` should fail if 1) description text exists for a data table column and 2) it is not visible in the 'description' component column

**Comment by rmanaem** [comment]
@jarmoza I believe the column descriptions are not initialized to their specific value inside the store.

**Comment by rmanaem** [comment]
The bug was produced due to a mismatch/typo in the spelling of the `Description` property in various places.
