### ISSUE TITLE
BUG: Annot-continuous not allowing passthrough to download page

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#387]
After a transformation heuristic is selected for the values of a continuous value column (e.g. 'Age'), the 'Save Annotation` button is not enabled and thus passthrough to the download page is blocked.

**Comment by rmanaem** [comment]
The issue seems to be stemming from `annotationCount` not being defined/referenced/updated inside anywhere.
#388 Will take care of that.

**Comment by rmanaem** [comment]
@jarmoza Now that #388 has been merged, could you check if the bug is fixed so we can close this?

**Comment by jarmoza** [comment]
@rmanaem We can close this issue now. There is something else holding up passage to the download page that is not related to the `annot-continuous-values` component. I'll drop a link to that new bug in this issue, but for now #388 closes this.
