### ISSUE TITLE
BUG: Not all available transformation heuristics function correctly.

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#392]
`euro`, `range`, and `string` transform heuristics appear to be broken

- `euro` replaces commas with full stops/periods. It should be the opposite
- `range` produces `NaN` for single values. Is this correct?
- `string` produces the string `'missing value'` - Is this (still) correct?

**Comment by rmanaem** [comment]
After discussion:

- `string` should be removed
- `euro` is fine
- `range` should be removed for (now perhaps revisit later?)
