### ISSUE TITLE
Implement Validation for the uploaded data dictionary

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/annotation_tool#393]
Following the discussion in issue #316, it was decided to enforce validation of the uploaded data dictionary based on the schema extracted from [pydantic models in CLI](https://github.com/neurobagel/bagel-cli/blob/main/bagel/dictionary_models.py).

*Implementation details to be specified*

**Comment by surchs** [comment]
This is linked #49

**Comment by surchs** [comment]
Closing as duplicate
