### ISSUE TITLE
getter to create JSON representation of discrete column

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#406]
Given a column mapped to a discrete category (e.g. "Diagnosis"), create a complete, schema compliant JSON object of all annotations we have made for this column.

Example from [our documentation](https://www.neurobagel.org/documentation/dictionaries/#diagnosis)
```json
  "group": {
    "Annotations": {
      "IsAbout": {
        "TermURL": "bg:diagnosis",
        "Label": "Diagnosis"
      },
      "Levels": {
        "PD": {
          "TermURL": "snomed:49049000",
          "Label": "Parkinson's disease"
        },
        "CTRL": {
          "TermURL": "purl:NCIT_C94342",
          "Label": "Healthy Control"
        }
      }
    }
  }
```
assume that
- the column was mapped to a discrete category (has entry in `state.columnToCategoryMapping`)
- `valueMapping` is incomplete
- all other data are BIDS or schema-compliant

TODO
- [ ] combine our annotations and existing annotations
- [ ] provide human readable labels (from hard-coded for now)
- [ ] provide unit tests

Data to grab

- `isAbout`
  - `state.columnToCategoryMap` for the "Label"
  - `state.categories[<categoryName>].identifier` for the IRI / TermURL
- `Levels` (in the annotations section)
  - `state.dataDictionary.annotated[<columnName>].valueMap` for the TermURL
  - `state.categoricalOptions[<categoryName>]` and then somehow find the right term (getter?)

**Comment by surchs** [comment]
blocked by Seb lack of time

**Comment by jarmoza** [comment]
After conferring with @surchs today, the task here is only to make changes for the existing identifiers and labels found in `store.state.categoricalOptions` and not others used outside of the annotation tool in NeuroBagel just yet.
