### ISSUE TITLE
getter to create JSON representation of continuous column

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#407]
Given a column mapped to a continuous category (only "Age" for now), create a complete, schema compliant JSON object of all annotations we have made for this column.

Ses example [here](https://www.neurobagel.org/documentation/dictionaries/#age)

assume that
- the column was mapped to a continuous category (has entry in `state.columnToCategoryMapping`)
- a `transformationHeuristic` has already been chosen
- all other data are BIDS or schema-compliant
- there are no "missing values" (because we haven't implemented that workflow yet)

TODO
- [ ] combine our annotations and existing annotations
- [ ] provide human readable labels (from hard-coded for now)
- [ ] provide unit tests

Relevant information to grab:

- `isAbout`
  - `state.columnToCategoryMap` for the "Label"
  - `state.categories[<categoryName>].identifier` for the IRI / TermURL
- `Transformation` (selected transformation heuristic)
  - `state.dataDictionary.annotated[<columnName>].transformationHeuristic` for the TermURL
  - `Nothing so far` for the LABEL
- `Description` and any other stuff
  - `state.dataDictionary.annotated[<columnName>]` (except `transformationHeuristic`)

**Comment by rmanaem** [comment]
To adhere to the schema outlined in [documentation](https://www.neurobagel.org/documentation/dictionaries/#age) following changes to `transformationHeuristics` property of the store are proposed:

- Remove `annot-continuous-values`
- Turn `transformationHeuristics` to an object where heuristics are the properties
- Each heuristic (property) has `TermURL` and `Label` which adhere to [documentation](https://www.neurobagel.org/documentation/dictionaries/#age)
- Update `getTransformOptions` getter to return the properties

**Comment by jarmoza** [comment]
@rmanaem Can you explain this proposal further?

> Remove annot-continuous-values

You want to remove the Vue component?

**Comment by rmanaem** [comment]
@jarmoza 

The `annot-continuous-values` property of `transformationHeuristics`

**Comment by rmanaem** [comment]
Ah yes thanks for the reminder!
