### ISSUE TITLE
Cypress Tests failures

### ISSUE THREAD

**Issue by Remi-Gau** [neurobagel/annotation_tool#424]
It seems that the Cypress tests have been failing for a while on master.

https://github.com/neurobagel/annotation_tool/actions/workflows/main.yml

Did not see any issues about that.

Not seen on any recent PR as they seem to target : dev_components_talk_to_store_directly

**Comment by surchs** [comment]
Yeah, I think you uncovered our little secret: these tests are currently expected to fail, but will stop failing once the long-lived refactor branch is finally merged. I think we're very close.

**Comment by Remi-Gau** [comment]
that was really well hidden... 

OK so should I hold off to merge all the dependabot PRs on this repo or should I merge them?

**Comment by Remi-Gau** [comment]
I guess can also probably retarget them to a different base branch...

**Comment by surchs** [comment]
no, merge them into main and ignore the failing tests, I think. @jarmoza wdyt?

**Comment by Remi-Gau** [comment]
note from today's meeting: let's wait before the refactor is done and merged before merging all of those
