### ISSUE TITLE
Swap 'Subject ID' for 'Participant ID'

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#425]
Proposal: Let's align terms used by the Neurobagel graph and the Annotation tool. Currently, the Annotation tool uses the term 'Subject ID' instead of 'Participant ID'.

- [ ] Find/replace all instances of 'Subject ID' for 'Participant ID'
- [ ] When the category is processed for annotated data dictionary output ensure the space is removed (as per https://www.neurobagel.org/documentation/dictionaries/#participant-identifier)

**Comment by surchs** [comment]
@rmanaem I think this is an internal refactor that isn't tied to https://github.com/neurobagel/planning/issues/35 so we should remove it from there. Do you agree?

**Comment by rmanaem** [comment]
> I think this is an internal refactor that isn't tied to https://github.com/neurobagel/planning/issues/35 so we should remove it from there. Do you agree?

Agreed.
