### ISSUE TITLE
Next release candidate for the Annotation Tool

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#441]
Now that the recent refactor is finished and merged with `master` as of PRs #437 and #440, we would like to prepare a public release for the annotation tool.

This task will follow the release process outlined in https://github.com/neurobagel/documentation/wiki/Release-process. 

I am opening this issue to outline the tasks needed for this release as well for any necessary, related discussion.

Below are the tasks needed to complete this release:

- [x] Create a tag and version number for this release candidate
- [ ] Create a 'new release' on Github
- [ ] Generate release notes with the help of `git log` (Since these do not exist for previous implementations, a separate task may be desirable in order to retroactively document those initial development changes and create a consistent changelog.)
- [x] #442 
- [ ] Save all of this work as a draft
- [ ] Discuss the release with the Neurobagel team
- [ ] Publish the release

**Comment by jarmoza** [comment]
As per https://semver.org/, I believe this release of the annotation tool should be numbered 1.1.0 given that

a. A version of the annotation tool ([the demo](https://annotate.neurobagel.org/)) has been available for public testing for some time now.
b. The refactor largely represents internal changes alongside the introduction of testing for all parts of the annotation tool. Several components functionality have changed as well making a "minor" but not "major" enhancement of the tool
c. The `package.json` for the repo has featured `1.0.0` since its creation.

**Comment by surchs** [comment]
fully agreed on the release. As we just discussed, I'd say let's go for `0.2.0` or something like that. And then make that number go up fast 🚀

**Comment by jarmoza** [comment]
The current milestone has been changed to `0.2.0`: https://github.com/neurobagel/annotation_tool/milestones

**Comment by jarmoza** [comment]
A draft version of the raw release notes can be found here: https://github.com/neurobagel/annotation_tool/releases/tag/untagged-2e9e24137a42d8d789ae

1. I separated out the Initial prototype and our iterations as `0.1.0`.
2. Anything after https://github.com/neurobagel/annotation_tool/issues/251 on December 13 is considered part of `0.2.0` (e.g. the refactor, new and refactored cypress tests)

**Comment by jarmoza** [comment]
Possible ideas for sections in Release Notes: https://gist.github.com/andreasonny83/24c733ae50cadf00fcf83bc8beaa8e6a

**Comment by alyssadai** [comment]
Hi @jarmoza, the release notes draft look good to me (I mostly focused on the `Overview`) and I think your reasoning for using version number `0.2.0` makes sense!

My one 🍒 suggestion would be to have the `Overview` section first in the notes, even before `Contributors`, so that it's most prominent and easiest to find.

**Comment by jarmoza** [comment]
Thanks @alyssadai.

Suggested changes made - https://github.com/neurobagel/annotation_tool/releases/edit/untagged-307f7e6f93a8ab27be4d

**Comment by surchs** [comment]
@jarmoza can we close this?
