### ISSUE TITLE
[ENH] Update documentation to include how-to-use instructions (with screenshots)

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

Now that we are about to publish the next major release of the annotation tool, it is time to update its documentation to include instructions guiding users on how to use its interface. This should include:

- [x] Badges for deployment status, component test status, e2e test status, node/nuxt/vue versions, and license type
- [x] Setup instructions (update if necessary)
- [x] Step-by-step interface instructions
- [x] Screenshots of the interface as the instructions move along through the annotation process via the tool's UI
- [x] Testing and License sections

**Comment by jarmoza** [comment]
@surchs @rmanaem Any comments on the above before I begin this?

**Comment by rmanaem** [comment]
I'd say include a section for testing and license, see [query tool README.md](https://github.com/neurobagel/query-tool#readme)

**Comment by jarmoza** [comment]
I'll add the appropriate badges to the top of the README as well.

**Comment by jarmoza** [comment]
@neurobagel/dev Does anyone have an opinion on best places to store images for a repo’s README?

The potential issue here is:

a) whether it's appropriate to put such images in a project's assets folder. My intuition is, "No."
b) limiting the work git has to do with images as it can increase clone/pull times

One possibility is storing such images in another repo like `neurobagel_media` and inserting the link of the desired image from that media repo into a README

**Comment by rmanaem** [comment]
I usually store them under an `img` dir in the root.

**Comment by jarmoza** [comment]
I'll do the same. If it becomes a problem with git times, we can reasses.

**Comment by jarmoza** [comment]
>use node v16.x LTS!

@rmanaem Is this warning up to date?  Or is this just the "last supported" version for Nuxt2? I'm currently using node 20.2.0 locally without issue.

**Comment by surchs** [comment]
https://github.com/neurobagel/annotation_tool/issues/411 I have this
