### ISSUE TITLE
Change trunk branch to `main`

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#443]
This is our only repo where the trunk branch is still called `master`. I think it'd be good to be consistent in how we call trunk, and everywhere else we now call it `main` - in line with [githubs default](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches#about-the-default-branch). 

Things to do:

- branch `main` off of HEAD `master`
- make sure nothing breaks (i.e. GH actions)
- make `main` the new default
- remove branch `master`

**Comment by rmanaem** [comment]
For reviewer: Please check the settings tab of the repo.

**Comment by surchs** [comment]
awesome @rmanaem, everything looks good. I think we can close this

**Comment by surchs** [comment]
sidenote: we can probably clean up a bunch of the old branches as well
