### ISSUE TITLE
[ENH] Add shortcuts 

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/annotation_tool#444]
Implement the following shortcuts in the tool for users to have easy access to

- [ ] Feedback shortcut to GitHub issues of the repo
- [ ] Website shortcut
- [ ] Repo shortcut
- [ ] Documentation shortcut

**Comment by jarmoza** [comment]
Following @surchs' [comment](https://github.com/neurobagel/query-tool/issues/117#issuecomment-1629659987), what would we like the subtitle to be for the Annotator?

**Comment by surchs** [comment]
> what would we like the subtitle to be for the Annotator

I think something like "harmonize phenotypic variables"?

**Comment by jarmoza** [comment]
Would "harmonize phenotypic data" be more comprehensive given the categorization and annotation steps?

**Comment by jarmoza** [comment]
My preference here is to move the links specified by @rmanaem [here](https://github.com/neurobagel/query-tool/issues/117#issuecomment-1629619486) to the lower left of the Annotation tool window.
![Screen Shot 2023-07-10 at 5 08 11 PM](https://github.com/neurobagel/annotation_tool/assets/4140162/09a4b92d-c0c3-405c-bd3d-50fb8a1975c4)

Thoughts @rmanaem and @surchs ?

**Comment by jarmoza** [comment]
Agreed. The footer would have to be sticky.

**Comment by jarmoza** [comment]
@surchs In looking over the possibility and given that the subtitle should probably be beneath the title, I think your solution of [justifying these new links to the right separated by vertical bar](https://miro.com/app/board/uXjVM3I8qXg=/?messenger=slack&utm_source=slack&utm_medium=messenger&utm_campaign=notifications&utm_content=board_shared&utm_term=messenger_analytics) is the best way to go.

![Screen Shot 2023-07-10 at 5 38 16 PM](https://github.com/neurobagel/annotation_tool/assets/4140162/7a28448c-eb3c-4fef-ae07-250d0dd60575)

**Comment by surchs** [comment]
This might also have the added benefit of wrapping these new fields in the responsive wrapping of the navbar in a collapsing menu when the screen size gets too small
