### ISSUE TITLE
[ENH] Adding 'Subject ID'/'Participant ID' to 'Annotations' section of data dictionary

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#477]
The output data dictionary currently does not contain the correct format for columns annotated as "about" participant id. See the docs: https://neurobagel.org/dictionaries/#participant-identifier

The place this change would take place is in the store mutation `alterColumnCategoryMapping`.

The cli is already in line with the spec and will be able to read the correct output.

Tasks
- [x] ensure output for column about "subject id " in the JSON follies spec
- [x] write test that ensures    "Identifies": "participant" is part of output

**Comment by surchs** [comment]
Demoting because not linked to OHBM/OpenNeuro priority - please ping here if you disagree
