### ISSUE TITLE
Configure and add Appzi feedback widget

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/annotation_tool#505]
Similar to the Appzi widget that's been added to https://query.neurobagel.org (see PR https://github.com/neurobagel/query-tool/pull/150), we should add one to the annotation tool to provide an easy feedback interface for folks who may not want to open a GitHub issue directly.

**Comment by rmanaem** [comment]
Unblocked by fb3d5fa7a3b2ac5045deb6b398bdba3bf4a5bd16

**Comment by rmanaem** [comment]
Since appzi uses the same token for implementing all surveys, I added a URL restriction for the query tool and annotation tool surveys which can be found by clicking on the survey, navigating to the `Collect` tab and scrolling down to the `Rules` section.
