### ISSUE TITLE
Check for dev build on PR

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/annotation_tool#508]
Add a new action or update a current one to run ```npm run dev``` on PRs to check if local dev env would break. This is needed as certain dev dependencies e.g., `eslint-plugin-prettier` are different when running the app in dev mode vs production mode.

**Comment by surchs** [comment]
We removed prettier: https://github.com/neurobagel/annotation_tool/pull/625 and I wonder if we can close this guy now. @rmanaem wdyt?
