### ISSUE TITLE
[ENH] Update annotation tool's vocabulary to align with rest of Neurobagel

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#521]
The annotation tool's "vocabulary" – meaning categories and Neurobagel identifiers – are out of sync with the more current versions of them being used by the API, CLI, and Query tool.

This issue is a place for discussion of that alignment and decision making on the implementation of that alignment.

**Initial questions/work**

- [ ] What is the current version of the Neurobagel vocabulary?
- [ ] What are the location(s) of the Neurobagel vocabulary in the annotation tool's code?
- [ ] How should this alignment take place?

**Initial proposal(s) for implementation**

Keeping in mind that it's possible that we would like this alignment to take place for the current [Douglas milestone](https://github.com/neurobagel/project/issues/105), we could:

1. Drop a static file containing the current Neurobagel vocabulary in the annotation tool's folders for it to read and use wherever that vocabulary is represented and used in its code, or
2. Determine if it is plausible to have Neurobagel's vocabulary sit at a single, external source of truth that the annotation tool could pull from at start up for it to read and use

**Comment by surchs** [comment]
https://neurobagel.org/term_naming_standards/#currently-used-namespaces

**Comment by jarmoza** [comment]
@rmanaem This could be possibly be tied in with an issue we've yet to address, re: `Subject ID`: #477

**Comment by jarmoza** [comment]
@alyssadai Could you take a look at this file in the annotation tool and make any notes on misalignments you see regarding the vocabulary?

https://github.com/neurobagel/annotation_tool/blob/master/store/index.js

We had already spotted the need to change from `bids:` prefix to `snomed` (with the corresponding ID number).

**Comment by surchs** [comment]
Ah cool.

For categorical terms: https://github.com/neurobagel/annotation_tool/blob/212487c55e96def8f643dc3ed8b7e733b40c5f39/store/index.js#L17-L47

For continuous (age) terms (transformations): https://github.com/neurobagel/annotation_tool/blob/212487c55e96def8f643dc3ed8b7e733b40c5f39/store/index.js#L153-L184

**Comment by surchs** [comment]
@jarmoza: do you have a suggestion for how we could replace these two sections with something we'd read from an external (`.js`?) file?

**Comment by alyssadai** [comment]
@jarmoza other than the namespace for sex, I think how the current included vocabularies are called look good to me.

I noticed that the `TermURL` for iso8601 is just "nb" right now instead of `nb:iso8601` - is that intentional?

**Comment by jarmoza** [comment]
>@jarmoza: do you have a suggestion for how we could replace these two sections with something we'd read from an external (.json or .js?) file?

@surchs Yes, we can either use JS `FileReader` as we are in the `file-selector` component or we can define these fields in a `.js` file and import them as we did in `dashQC`. From experience, the latter is faster.

**Comment by jarmoza** [comment]
>I noticed that the TermURL for iso8601 is just "nb" right now instead of nb:iso8601 - is that intentional?

@alyssadai I believe the implementation of this transformation just remains incomplete.

By the way, this url [http://neurobagel.org/vocab/](http://neurobagel.org/vocab/) is dead.

**Comment by jarmoza** [comment]
Recommended solution(s) for importing this information via a flat file (in an appropriate folder - maybe `assets`):

1. JSON: This could be loaded via JS's `FileReader` (as we do in `file-selector`) in the Vuex store's `nuxtServerInit()` function (not currently defined in `index.js`) https://v2.nuxt.com/docs/directory-structure/store/#the-nuxtserverinit-action
find link for nuxtServerInit()
2. JS: Since JavaScript treats variables in JS files like it would what is loaded from a JSON file, we can Import predefined objects in JS file that would be imported in the same way as the imports currently taking place at the top of `index.js` This should be the fastest solution, but will need testing to make sure if those variables are available at the time of the store variable assignment.

All loaded values would be assigned to the current vocab keys in `store.state`.

**Comment by jarmoza** [comment]
@surchs and @rmanaem Closing with recommended potential solutions.
