### ISSUE TITLE
Check if `annot-explanation.cy.js` is still flaky

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/annotation_tool#550]
Since bumping cypress to 13.0.0, the `annot-explanation.cy.js` has been acting flaky i.e., passing and failing randomly (see #546).
We pinned the node version in the cypress component test action and it seemed to resolve the issue. Let's make sure that's the case.
Resources:
[Cypress docs](https://docs.cypress.io/guides/cloud/flaky-test-management)

- [ ] understand or at least get a good intuition on what is causing this test to fail. Although the test is not important, understanding how cypress' changes are impacting previously running tests is. So we may have to spend more time than the tiny test itself would warrant to figure this out
- [ ] once we know what's wrong, see if we can refactor the test / remove it. as far as I can tell, currently the test is almost testing the bootstrap-accordion component itself

**Comment by rmanaem** [comment]
It's still flaky see [this log](https://github.com/neurobagel/annotation_tool/actions/runs/6239728915/job/16938432858).

**Comment by surchs** [comment]
For spec: I think we should do two things:

- understand or at least get a good intuition on what is causing this test to fail. Although the test is not important, understanding how cypress' changes are impacting previously running tests is. So we may have to spend more time than the tiny test itself would warrant to figure this out
- once we know what's wrong, see if we can refactor the test / remove it. as far as I can tell, currently the test is almost testing the bootstrap-accordion component itself

**Comment by surchs** [comment]
@rmanaem anything else or is this fully described?

**Comment by rmanaem** [comment]
I believe it is sufficiently described.

**Comment by rmanaem** [comment]
> understand or at least get a good intuition on what is causing this test to fail. Although the test is not important, understanding how cypress' changes are impacting previously running tests is. So we may have to spend more time than the tiny test itself would warrant to figure this out

It seems that the issue was caused by bumping the [`cypress-io/github-action` from v5 to v6](https://github.com/neurobagel/annotation_tool/pull/518).

To address the issue, dependabot we'll be instructed to ignore major version updates for `cypress-io/github-action`.

**Comment by rmanaem** [comment]
well it turns out we were duped by 4 consecutively successful test runs and the test is still flaky, see [latest logs](https://github.com/neurobagel/annotation_tool/actions/runs/6303697428/job/17113497307) that failed after instructing dependabot to ignore major version updates for `cypress-io/github-action`.

**Comment by surchs** [comment]
Yeah, this is really frustrating. But I think we'll have to accept that this one component has become flaky and we don't know why. Given that it is not a critical component, and that the app likely will see some refactoring again in not too long for vue3, I'd say: let's stop using the collapsible vue-bootstrap element and just use a card or similar
