### ISSUE TITLE
Allow annotation of healthy controls

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/annotation_tool#553]
Right now there is no way for a user to indicate that a specific value in the data-table means that the corresponding subject is a healthy control. Further, there is no clear design for a workflow that would let a user provide this annotation. E.g. if there is a column "healthy control" with values "True" and "False", what should they do. Or if the information is in a diagnostic column

We decided to use the following workflow

- any column that has info on "isControl" should get classified as about "Diagnosis"
- on the Annotation page, we add a "isControl" button
- the user should click this button to signal that a specific value in the "Diagnosis" column indicates that the subject is a control
- if the column only contains info on isControl (e.g. dummy coding, True/False), then the remaining values should be classified as missing

- [x] Design a generic workflow to annotate "healthy control", reusing existing workflows as much as possible
- [ ] Implement the workflow by adding the required UI components and logic
- [ ] provide tests for these cases:
  - healthy-control status is part of a generic "Diagnosis" column
  - healthy-control status is dummy-coded, e.g. as a "is_healthy_control" column
  - there is no information on healthy control / the annotation is not made
- [ ] make sure the is_control status successfully makes it into the output .json

**Comment by surchs** [comment]
@rmanaem does this look reasonable to you / anything missing?

**Comment by rmanaem** [comment]
Yea it looks good but I'd like to discuss the workflow and the UI elements.
