### ISSUE TITLE
Create a component to show missing data

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#58]
A user annotating e.g. age on the annotation page should see a representation of all of the values we think are representing missing values in the columns that are "about" age.

**data in**:
- list of columns (and their names) previously categorized as "about" age
- the raw values from these columns
- if available, the mappings for these raw values from the data dictionary
- a list or index of unique values we think may represent missing data (this could also generated by a function inside the component)

**behaviour**:
- [ ] the component shows me every value we consider to reflect "missing data" (e.g. table, list, ...)
- [ ] together with these values, I can see the name of the column the value came from (e.g. "XX" could stand for missing data in one column but not in another)
- [ ] there is an intuitive way for me to label a value as "not missing data". e.g. with a button that is right next to the value, or a checkbox, ...
- [ ] when I complete the action to label a value as "not missing data" (e.g. press a button), it disappears from the values shown in the component

**data out**:
- a list of values and the columns they came from, that reflect "missing data"

To discuss:
- there should probably also be a way to undo this operation or declare values as "missing" in a standardized way
- where should we keep track of these missing values?

Accept when:
- [ ] in any other category annotation component (sex, diagnosis, ..., but not age) I can designate a value as missing and it will be displayed by the missing value component for the corresponding category. See #117
- [ ] in the missing value component, I can designate a value that was previously classified as missing to be not missing (e.g. remove). This will remove the value from being shown in the missing value component and will also list the value again for annotation in the corresponding annotation category component
- [ ] values displayed in this component (e.g. labeled missing) are displayed with their column name (from the table), and with any description derived from a data dictionary if available.

**Comment by jarmoza** [comment]
@surchs Can you explain a bit more what you mean by the word "missing" for this component?

**Comment by surchs** [comment]
Yeah! So let's assume a column `"Age"` has the values `['11.0', '12', 'n/a', 'XXXX', '-', '14.1', '9999']`. Then `n/a`, `XXXX`, `-`, and probably `9999` are likely to reflect a missing value or some entry error, rather than an actual age. We are unlikely to see so many different ways of describing "missing" data in one dataset, but it's not unlikely that there are several, e.g. because of typos (i.e. `n/a` and `na`) when data were entered by hand.

Particularly for continuous variables like age (where we cannot ask the user to annotate each unique value), we will want to make an educated guess about what values reflect "missing values". But I think we may get that wrong some times. And for this reason, there should be a small component that shows the user the values we consider to be "missing" values, and allows the user to tell us if any of them are instead "real" values - so we can include them in our transformation attempt.

**Comment by jarmoza** [comment]
🙏 Thank you.

**Comment by jarmoza** [comment]
> if available, the mappings for these raw values from the data dictionary

@surchs Can you flesh this out a bit more?

**Comment by surchs** [comment]
The idea was here: 
- take the values we think reflect "missing data"
- look them up in the data dictionary under the "levels" key for categorical data (see the [BIDS specs for participants.json files](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#participants-file))
- if we find any descriptions for the values in the data dictionary, add them to the missing data component as a reminder for the user

Let's say:
- we annotate the "Sex" category
- a column called "participant_sex" was labeled as "about" Sex
- one of the values in this column is `"na"`
- we pull this out (through sheer foresight) as a suspected "missing value"
- we look up `"na"` in the data dictionary for `"participant_sex"`:

Let's say the data dictionary looks like this:
`participants.json`:
```
"participant_sex": {
        "Description": "the self reported gender of the participant",
        "Levels": {
            "m": "male",
            "f": "female",
            "na": "participant did't answer the question"
```
Then we could show the string `"participant did't answer the question"` together with the suspected "missing data" value `"na"` to the user in order to help them make a better judgment. 

Now, realistically, this is not going to be very important often. Because values are most likely going to be either easily identifiable as missing even without the extra description, or - more likely - missing values will not have a description in the data dictionary. So in short: I would rate this feature as not very important for now

**Comment by jarmoza** [comment]
This is all good and clears things up, but just one more question.

> we pull this out (through sheer foresight) as a suspected "missing value"

This sounds like we are going to have custom code for each of the categories that has some hardcoded/reg-exed means of determining if a value looks out of the ordinary.  Is that correct?

**Comment by surchs** [comment]
I think that's an open question. The way I think about it at the moment is that most categorical columns will have a number of unique values that we can just show the user in full. Then they can tell us which of these are "missing values". E.g. a diagnosis column with `['pd', 'ctl', 'na']` are three lines in a table. And if `'na'` is the "missing value", the user would select "missing" from a dropdown or checkbox for this row. 

Even if we have to handle many categories in a column (or set of columns), e.g. for "assessment tools", we still have to ask the user to annotate each category. So one or two extra categories for "missing" data are not going to break things.

The only place where this doesn't work is for numeric / continuous data. But as far as I can see, this is also the case where identifying missing values is going to be easier. E.g. "should be a number > can I cast it to a number > no > probably missing value" or "should be a number between 1 and 100 > this is a negative number > probably missing". etc.

I think we'll have to see if this is enough. If you have some ideas. Let me know what you think

**Comment by jarmoza** [comment]
It'll be tricky code, but definitely not impossible. I think the best way to do this is write out the types of data and then list expected values and expected missing values. This way we can write out a series of general tests in the form of methods that can be reused for each type of data (column values).

**Comment by surchs** [comment]
Yeah, I think that makes sense to me. And what I meant to add but didn't is: for some obvious cases (e.g. empty string, wrong data type, etc) where it makes sense to capture via regex, it might make sense to have category specific rules. But alternatively we can also choose to only show this component for categories with continuous data

**Comment by jarmoza** [comment]
Is there an expected range field(s) in BIDS that you are aware of that is akin to the 'Levels' field?

**Comment by surchs** [comment]
I'm not aware of that. I know you can provide `"units"` in the BIDS data dictionary. But I think value ranges are not part of BIDS to my knowledge. We should check that though, and if it really doesn't exist, this may end up being a useful contribution to BIDS.

**Comment by jarmoza** [comment]
Would we consider outliers for numeric data to be "missing"?

**Comment by jarmoza** [comment]
@surchs Also, can I expect the column data type to be given to this component or will I have to derive it via the input data?

**Comment by surchs** [comment]
@jarmoza, sorry, missed these:
> Would we consider outliers for numeric data to be "missing"?

I think for now, no. But that's a good idea and we could keep it in mind for a later addition. Make an issue?
> can I expect the column data type to be given to this component or will I have to derive it via the input data

Ah, I think that's what we ended up discussing on slack today, right? Yeah, I'd say we should could pass this to the component. The parent component (containing the category-specific annotation tab) can have the category type hard-coded and pass it along. Sound good?
