### ISSUE TITLE
The assessment tool workflow is horizontally aligned below the column workflow

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#612]
At the moment, the annotation workflow uses different layout columns and ends up being split evenly across the viewport. Instead it should be aligned with the column  annotation workflow so that:

~- [ ] the "select tool" dropdown window sits below the "pick category" table, with the same width~
- [x] once a tool is selected, the "here is your tool" table sits below the dropdown, again same width
- [x] The "here are the columns you said were about assessment tools" table should sit below the "column-table", same width

**Comment by rmanaem** [comment]
Unfortunately achieving all three checkboxes of this issue proved to be quite a difficult task without refactoring the `category-toolgroup` into two separate components.
