### ISSUE TITLE
Descriptions for discrete values are not shown in the annotation workflow

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#616]
At the moment, any "Levels" descriptions we get from the BIDS data dictionary (i.e. for discrete columns) are just ignored in the annotation views:

![image](https://github.com/neurobagel/annotation_tool/assets/1302022/1d7267bb-f3d1-448b-b132-645127e63d4b)

but see

![image](https://github.com/neurobagel/annotation_tool/assets/1302022/66466fd0-f176-460b-9b4b-cdc536cf06f3)

This is (hopefully) and easy fix, but to make sure it doesn't come back we need both:

- [ ] Show "Levels" descriptions for values on the appropriate discrete annotation workflows (i.e. "Sex" and "Diagnosis"?)
- [ ] Write a test (component ?) that makes sure this actually works (and stays that way)

**Comment by surchs** [comment]
The problem here is case sensitive attribute access:

https://github.com/neurobagel/annotation_tool/blob/d4be4f28c1c56268796b1de72c0603d1d009029d/store/index.js#L644-L653

we look for lowercase `levels` but in our input files they are uppercase `Levels`. This is not too bad, but it also means we should definitely make sure all keys are uppercase when we get to #49!

**Comment by surchs** [comment]
The other side of this is that we have to make sure we're using correct mocks in our tests. The tests passed because in our test mocks we **did** use lower case `levels`:

https://github.com/neurobagel/annotation_tool/blob/d4be4f28c1c56268796b1de72c0603d1d009029d/cypress/unit/store-getter-getValueDescription.cy.js#L7-L13

So that needs to be changed

**Comment by surchs** [comment]
The final issue is that the main example we're using actually has the wrong Levels for the the table data we're loading. For sex 

- the table uses 1 and 2
- the data dictionary uses `F` and `M`

So we would never see the descriptions, even after resolving the bug

**Comment by rmanaem** [comment]
I reckon its better to configure all tests to use the `example_synthetic` files that have been updated very recently. wdyt @surchs?
