### ISSUE TITLE
Cleaner visual interface for assessment tool missing value annotation

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/annotation_tool#620]
Since all the unique for a given column are presented to be annotated as missing on the same page, it would be helpful if all column values were visually grouped in some way (with a gap between columns, color-coded, etc.) to make it a bit easier to keep track of what column you are annotating.

<img width="722" alt="image" src="https://github.com/neurobagel/annotation_tool/assets/65699389/c4be88ef-1fe9-495c-b259-6c16f4f7608e">

TODO
- [ ] Figure out what visual elements are practical to highlight the visual separation between rows that belong to the same column
- [ ] propose the visual element (check off with someone else)
- [ ] implement this visual element (assuming the table will not be sortable)
- [ ] write a test for it

**Comment by surchs** [comment]
Two options I can see:

- have the "column" column span multiple rows: https://bootstrap-vue.org/docs/components/table#comp-ref-b-td-props
- see if we can use custom styling to add another color on top of the "striped" aspect of the row styling (e.g. light blue color) to do a meta-stripe (i.e. color on/off between columns)
