### ISSUE TITLE
Remove `FromInt` transformation and supporting only `FromFloat`

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/annotation_tool#636]
This may be simpler and less confusing for the user when they have a column with a mix of float and int ages

**Comment by willtryagain** [comment]
Hi, 

My understanding is that we need to remove Int from (https://github.com/neurobagel/annotation_tool/blob/f96f3e2b954b2c61c964e6c32216d81ff16c466c/store/index.js#L120).

Can you please tell how to attempt this?   Any particular changes for the age column ?

Thanks

**Comment by rmanaem** [comment]
Hi @willtryagain,
Unfortunately, this issue requires internal discussion to be addressed.
