### ISSUE TITLE
Warn user about incomplete annotation before downloading

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#637]
At the moment, a user can make an incomplete annotation (i.e. leave out some required steps to make valid neurobagel .json) and our annotation tool will not say anything / emit any warning. 

An example:

If
- I label a column as "about" "Age"
- I then never pick any "Transformation" for the "Age" columns (e.g. because I forget)

Then
- the annotation tool will happily turn the "next" button green and let me proceed to the download page
- and will let me download a .json that is not actually valid under our own schema (because it is missing the "Transformation" key). See also #597

I think we originally made that change because we thought a user might want to stop half-way through an annotation and pick it up later - and we shouldn't prevent them from downloading what they have until then. However, our tool isn't yet able to load our own annotations again. And even if we want to support this, we should definitely give a warning.

TODO:

- [x] validate the JSON we're about to give back to the user against our data dictionary json schema
- [x] Emit a warning on the download page or before if a user proceeds to download a .json file that isn't valid / user hasn't completed all annotation steps
- [ ] propose a way to keep up to date on the data dictionary schema

**Comment by alyssadai** [comment]
See also https://github.com/neurobagel/bagelschema
