### ISSUE TITLE
Conversion to Vue3/Nuxt3

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#65]
In order to stick with our current development timeline and to avoid potential issues with code that is less-documented (e.g. Nuxt 3 Beta), we will approach the tool's upgrade to Vue3/Nuxt3 at first as experimental.

When @surchs or myself feel we have time we will attempt to do the upgrade/conversion, we will create either a new branch or a new repo (whatever makes sense).

This issue serves as a reminder about attempting this upgrade.

**Comment by jarmoza** [comment]
Of note, for this upgrade is the question over the reactivity bug that @surchs and I have come across. Whether it relates to Nuxt or Vue itself is unknown.

As it sits, we have come across a situation where a JavaScript object created via traditional means like `{}` or `new Object()` is only noticed as being updated by Vue too late to update the state of the app in the current 'frame' of the Vue lifecycle. This results in a delayed reaction to the object's update, the reaction only being visible in the next Vue 'frame.' Instantiation of the object via `Object.fromEntries`, however, offers same-'frame' reactivity.

The hope is that an upgrade may overcome this bug, but for now the reasonable workaround has been to use `Object.fromEntries` for instantiation of objects that require reactivity to changes to them.

**Comment by surchs** [comment]
Closing as not yet planned, we'll first have to explore in more detail whether the ecosystem is ready. That's not a priority now.
