### ISSUE TITLE
Let's consider a test framework

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#69]
Now that things are starting to become a bit more complex, we should consider implementing tests.
There are Vue specific test frameworks: https://v2.vuejs.org/v2/guide/testing.html#Component-Testing. There is also a Nuxt extension but this doesn't appear to be very active or widely used: https://test-utils.nuxtjs.org/

We should:
- [ ] decide what kind of testing is most relevant (e.g. unit, end-to-end...) and focus on that for now
- [ ] explore some frameworks, check other projects for inspiration, or ask around
- [ ] figure out how the setup would work for the test framework
- [ ] also figure out how to set up continuous integration for that

We should have something that at least ensures we don't break any major interface functionality or alerts us if we do.

**Comment by jarmoza** [comment]
Agreed, but I think we should only prioritize this after we have the simple demo for the tool.

**Comment by surchs** [comment]
Based on https://v2.vuejs.org/v2/guide/testing.html
I say we adopt:
- Jest for unit and component testing: https://github.com/facebook/jest
- Cypress for functional testing: https://github.com/cypress-io/cypress

**Comment by surchs** [comment]
I think we can close this with https://github.com/neurobagel/annotation_tool/pull/165, @jarmoza do you agree?

**Comment by jarmoza** [comment]
Agreed.
