### ISSUE TITLE
Consider having components and pages call conditional functions on data state instead of explicit checks

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#72]
Reproducing some text from PR https://github.com/metaneuro/annotation_tool/pull/66

Getters that act as boolean conditionals can be used to ask the state of data in the store and not have our pages/components worry about what that check entails.

This is generally considered good programming practice where the details of conditional checks are kept close to their data sources. In fact, I was thinking we may want to consider doing this throughout the app where applicable. There are already a few instances where this scenario pops up. The relevant example was getter `isColumnLinkedToCategory` in the store and whether or not it should remain in the codebase. (See isDataTableLoaded and isDataDictionaryLoaded, also for instance.)

**Comment by surchs** [comment]
@jarmoza I think we can close this one, yes?
