### ISSUE TITLE
Make custom version where the Assessment tool list comes from SNOMED-CT

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#769]
We have now heard many times that Cognitive Atlas has insufficient coverage of clinical assessments (makes sense). It seems that SNOMED-CT has better coverage. Long term, we want to add a "clinical assessment" category and rename the current assessments to "cognitive assessment" - or something along those lines. 

This issue is about an experimental, short term change that we will not publicly deploy. We want:

- [x] the options in the "Assessment tool" dropdown should come from SNOMED-CT, not Cognitive Atlas
- [x] the option names should be the preferred names from SNOMED-CT
- [x] the internally stored values when a user selects an assessment should be the SNOMED-CT unique identifiers (very much like we already do for diagnosis)
- [x] the values stored in the output data dictionary for "isAbout" should be SNOMED-CT unique identifiers (with snomed prefix)

The goal is not (necessarily) to make graph files with the data dictionaries, we may only use the data dictionaries to manually harmonize clinical assessments across a number of datasets to find out how many participants have these tools.

@rmanaem: this is the issue I mentioned to you yesterday.

**Comment by rmanaem** [comment]
@surchs What are your thoughts on creating an env var that switches between the two vocabs for assessment tool options?

**Comment by surchs** [comment]
up to you, but I'd prefer to not ship something to production that can be user configured to run SNOMED. When we switch we should switch for everyone

**Comment by rmanaem** [comment]
For reviewer: check the app preview on the open draft PR to view the changes and discard the failing test cases as they're specific to terms from cogatlas.
