### ISSUE TITLE
Move to deploy-on-release

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#790]
Recent events have shown us that deploying on every merge to main is risky, because you can deloy silly things at inopportune times. Let's follow the good examle of our dockerized tools and only deploy to prod on a release. 

Specific todos:
- [x] Change our deployment process to only run on a release
- [x] Find a way to have a running "nightly" version with a persistent name (i.e. not the staging previews, but maybe netlify works)
- ~~[ ] Setup / carry over the auto-release workflow from other projects~~

**Comment by surchs** [comment]
Let's not setup the auto-release. This repo is going to get its refactor in the not too distant future. So let's just release by hand for now and save ourselves the setup.

**Comment by rmanaem** [comment]
>  Find a way to have a running "nightly" version with a persistent name (i.e. not the staging previews, but maybe netlify works)

@surchs Did you have something in mind for this?

We already have netlify on PRs here like we do in the query tool and the openneuro UI:
https://github.com/neurobagel/annotation_tool/pull/798#issuecomment-2411349016

**Comment by surchs** [comment]
Yes @rmanaem, in fact the nightly builds (whatever the HEAD of main branch is) are already hosted here: https://neurobagel-annotator.netlify.app/ - we just never use that. Maybe we could link this deployment with a nice clear warning that it is unstable/can break from the repo description or README
