### ISSUE TITLE
v-for statement over array causes DOM mismatch between server and client

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#80]
The v-for statement below was causing a mismatch between client-side and server-side
DOM. In particular, the first element in "pages" (Age) was rendered twice. The error message was:

```
      Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content.
      This is likely caused by incorrect HTML markup,
      for example nesting block-level elements inside <p>, or missing <tbody>.
      Bailing hydration and performing full client-side render.
```

The best answer I found online was this pretty useless stackoverflow answer:
https://stackoverflow.com/a/61375490/1302009 suggesting that this might be due to some
async getting of Array data.

I forced this block to be rendered client-side only in https://github.com/metaneuro/annotation_tool/commit/4be7c3cb76e39ec573e33a0ff78d9c9281e91123 and that fixed it for now
See: https://nuxtjs.org/docs/features/nuxt-components/#the-client-only-component

However, this was not a good solution. I think @jarmoza you figured out what caused this?

**Comment by jarmoza** [comment]
Addendum: If I force reload the annotation page, the double 'Age' tab returns. Going through the tool with typical flow does not produce the double age tab. So it seems that whatever issue this is, it may have to do with beginning with the annotation page instead of with the landing page.

**Comment by jarmoza** [comment]
Another possibility for this is: let's use something else other than `b-tabs`

**Comment by surchs** [comment]
Thanks @jarmoza. Let's check this out again after the demo. One thing I'd like to see is what happens when we use the navigation toolbar to switch between the pages (and load the annotation page like that). Although reloading is maybe a bit unusual, I am not sure why this would happen. Maybe something to file an issue with the vue/nuxt folks about too eventually.

I'm also open for trying something other than `b-tabs` if that helps after the demo.

**Comment by jarmoza** [comment]
> One thing I'd like to see is what happens when we use the navigation toolbar to switch between the pages (and load the annotation page like that).

From my testing 'Age' does not appear twice via navbar navigation with my 'fix.'

**Comment by jarmoza** [comment]
Vue also issues this warning regarding `no-ssr` tags:

`<no-ssr> has been deprecated and will be removed in Nuxt 3, please use <client-only> instead`
