### ISSUE TITLE
Being able to search by instrument abbreviations as well as full names

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#821]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### New feature

Several users mentioned that it is difficult to find assessments because they are often known by their abbreviation, but we only let users search the full name. It would be nice if an assessment could be discovered through type-ahead suggestions in the dropdown menu for the full name **and** the abbreviated name.

### Unclear documentation

Expanded from #815

**Comment by rmanaem** [comment]
This is mostly a question whether this can be extracted from the vocabulary and provided to the annotation tool as a file.
