### ISSUE TITLE
Make missing values and columns section start collapsed

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#824]
![Image](https://github.com/user-attachments/assets/1d24ffc6-d02a-414d-9a13-dd44593195ed)

The "Review the annotated columns" and "Missing Values" sections take up so much space that the really important annotation section usually starts off-screen. These two sections are not really that important, so we should:

- [x] Make the cards for each section collapsible
- [x] Start each section/card collapsed

We used to have the "Instruction" card collapsible, so that would be a good starting point for bringing this functionality back

**Comment by rmanaem** [comment]
Addressed in #827
