### ISSUE TITLE
Add clearer descriptions on the annotation tool

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#826]
Three improvements

1. Add a explanation text below the categorization component (variables <-> column names table) that is always visible and explains how to annotate the assessment tool workflow
2. Collapse or re-order to the bottom the "Review the annotated columns" and "Missing Values" cards on the annotation page so the new order is
    1. Explanation
    2. Annotation workflow
    3. Review annotated columns
    4. Missing Values
3. Add explanation string above the age heuristic dropdown in the age-annotation card.

TODOs:

- [x] Add a explanation text below the categorization component
- [x] Add placeholder text in assessment tool dropdown window that says "Add Assessment" or something @surchs 
- [x] Collapse or reorder cards on Annotation page (for all variables)
- [x] Add explanation text above age heuristic dropdown. Something like "Select type of age"
- [ ] Update the explanation text for different variables to be a bit more descriptive: @surchs 

## Examples
![Image](https://github.com/user-attachments/assets/81116c24-d095-4ef0-8cfc-4688a7bbcc76)
Age annotation string

![Image](https://github.com/user-attachments/assets/fbb94e7e-95ec-4ce7-8ad4-ac107c9d51c5)
Assessment tool explainer text

![Image](https://github.com/user-attachments/assets/c087d8d5-1a51-4b12-803e-810e93b5cb66)
Dropdown placeholder text

**Comment by surchs** [comment]
@rmanaem I added a couple of examples for what the goal here would be. I'll draft up the text for you that we want to add for the annotation tools. For the dropdown placeholder text feel free to go with something short and clear - or let me know if you want to discuss.

**Comment by rmanaem** [comment]
@surchs I made most of the changes outlined in the issue description and opened a draft PR: https://github.com/neurobagel/annotation_tool/pull/827
Left a couple of the texts that require editing for you, namely the categorization text as lorem ipsum. It should be easy to find and replace but let me know if you want me to do it.

**Comment by surchs** [comment]
Awesome, thanks so much @rmanaem! This was lightning fast!
