### ISSUE TITLE
v-for use without key in annot-columns.vue is causing warning

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#83]
I'm getting the following warning from here:

>  WARN  in ./components/annot-columns.vue?vue&type=template&id=6b92ec6b&        friendly-errors 10:51:55
> 
> Module Warning (from ./node_modules/vue-loader/lib/loaders/templateLoader.js): friendly-errors 10:51:55
> (Emitted value instead of an instance of Error) <b-list-group-item v-for="[columName, categoryName] in Object.entries(filteredColumns)">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

_Originally posted by @jarmoza in https://github.com/metaneuro/annotation_tool/pull/77#discussion_r832291449_

**Comment by surchs** [comment]
@jarmoza, can this be closed?

**Comment by jarmoza** [comment]
Yes, this has been addressed.
