### ISSUE TITLE
Update dependencies (if possible)

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#88]
`npm install` now produces several warnings to update the dependencies of our project. While some may be related to us not yet using Vue 3 and Nuxt 3, it may be possible to update others.

When we have a moment, one of us should take a moment to investigate if it's possible to update dependency versions.

<img width="1280" alt="Screen Shot 2022-03-25 at 10 41 54 AM" src="https://user-images.githubusercontent.com/4140162/160142911-ab50db6a-9dc2-4a00-9229-94d9742b1237.png">

Our dependencies are pretty outdated (e.g. https://github.com/neurobagel/annotation_tool/issues/293), there hasn't been an update to them in a while. We should 

- [ ] research ways to keep the package.json up to date
- [ ] discuss the options with the team and make a decision
- [ ] document the process necessary to update dependencies

This isn't about implementing the update, this is about finding a good solution for the general problem of "all my JS dependencies are old now".

There is also https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions

**Comment by surchs** [comment]
That's a great idea @jarmoza. While we're at it, we could also consider implementing https://github.com/dependabot to be notified if any vulnerabilities exist in the currently pinned versions of our dependencies!

**Comment by rmanaem** [comment]
I think we can close this now that dependabot is set up. @surchs Do you concur?

**Comment by surchs** [comment]
I concur :)
